import type { PrivacyPolicy } from '../../types/privacy';

/** Convert a section title to a GitHub-flavoured Markdown anchor slug. */
function toAnchor(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-');
}

/**
 * Export a PrivacyPolicy as a clean Markdown string.
 *
 * Structure:
 * ```
 * # Policy Title
 * _Effective: date | Version: X | Org Name_
 *
 * ## Table of Contents
 * - [Section Title](#anchor)
 *
 * ## 1. Section Title
 * Section content...
 * ```
 */
export function exportMarkdown(policy: PrivacyPolicy): string {
  const includedSections = policy.sections.filter((s) => s.included);

  const title = policy.title || 'Privacy Policy';
  const orgName = policy.organizationInfo.name || 'Organisation';
  const version = policy.version || '1.0';

  const effectiveDateStr = policy.effectiveDate
    ? new Date(policy.effectiveDate).toLocaleDateString('en-NG', {
        day: 'numeric',
        month: 'long',
        year: 'numeric',
      })
    : new Date().toLocaleDateString('en-NG', {
        day: 'numeric',
        month: 'long',
        year: 'numeric',
      });

  const lines: string[] = [];

  // ── Title & metadata ───────────────────────────────────────────────────
  lines.push(`# ${title}`);
  lines.push('');
  lines.push(`_Effective: ${effectiveDateStr} | Version: ${version} | ${orgName}_`);
  lines.push('');

  if (policy.organizationInfo.website) {
    lines.push(`**Website:** ${policy.organizationInfo.website}  `);
  }
  if (policy.organizationInfo.privacyEmail) {
    lines.push(`**Privacy contact:** ${policy.organizationInfo.privacyEmail}  `);
  }
  if (policy.organizationInfo.website || policy.organizationInfo.privacyEmail) {
    lines.push('');
  }

  lines.push('> This privacy policy is compliant with the **Nigeria Data Protection Act (NDPA) 2023**.');
  lines.push('');
  lines.push('---');
  lines.push('');

  // ── Table of Contents ──────────────────────────────────────────────────
  if (includedSections.length > 0) {
    lines.push('## Table of Contents');
    lines.push('');
    includedSections.forEach((section, i) => {
      const anchor = toAnchor(`${i + 1} ${section.title}`);
      lines.push(`${i + 1}. [${section.title}](#${anchor})`);
    });
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  // ── Sections ───────────────────────────────────────────────────────────
  includedSections.forEach((section, i) => {
    lines.push(`## ${i + 1}. ${section.title}`);
    lines.push('');

    const content = (section.template || section.defaultContent || '').trim();

    if (content) {
      // Preserve list items; wrap other lines as-is
      const contentLines = content.split('\n');
      for (const line of contentLines) {
        const trimmed = line.trimEnd();
        // Already a markdown list item or blank line — pass through
        if (trimmed.startsWith('-') || trimmed.startsWith('•') || trimmed === '') {
          lines.push(trimmed.replace(/^•/, '-'));
        } else {
          lines.push(trimmed);
        }
      }
    }

    lines.push('');
    lines.push('---');
    lines.push('');
  });

  // ── Footer ─────────────────────────────────────────────────────────────
  lines.push(`_Generated by **NDPA Toolkit** \u2014 ${orgName} \u2022 Version ${version}_`);
  lines.push('');

  return lines.join('\n');
}
