/**
 * NDPA Compliance Schema — generated by create-ndpr
 * Organisation: {{ORG_NAME}}
 * DPO: {{DPO_EMAIL}}
 *
 * Covers:
 *   - consentRecords              — NDPA §25–26 (consent & withdrawal)
 *   - dsrRequests                — NDPA Part IV §34–38 (data subject rights)
 *   - breachReports              — NDPA §40 (72-hour breach notification)
 *   - processingRecords          — ROPA (accountability principle)
 *   - dpiaRecords                — NDPA §34(3) (impact assessments)
 *   - lawfulBasisRecords         — NDPA §25 (lawful basis register)
 *   - crossBorderTransferRecords — NDPA §41–42 (cross-border transfers)
 *   - auditLog                   — §44 audit trail
 *
 * Prerequisites: drizzle-orm, @paralleldrive/cuid2
 * Run `drizzle-kit push` to apply.
 */

import {
  pgTable,
  text,
  timestamp,
  json,
  boolean,
  integer,
  index,
} from 'drizzle-orm/pg-core';
import { createId } from '@paralleldrive/cuid2';

// ---------------------------------------------------------------------------
// ndpr_consent_records — NDPA §25–26
// ---------------------------------------------------------------------------

export const consentRecords = pgTable(
  'ndpr_consent_records',
  {
    id:           text('id').primaryKey().$defaultFn(() => createId()),
    subjectId:    text('subject_id').notNull(),
    consents:     json('consents').notNull(),
    version:      text('version').notNull(),
    method:       text('method').notNull(),
    lawfulBasis:  text('lawful_basis'),
    ipAddress:    text('ip_address'),
    userAgent:    text('user_agent'),
    createdAt:    timestamp('created_at').defaultNow().notNull(),
    revokedAt:    timestamp('revoked_at'),
  },
  (t) => ({ subjectIdIdx: index('consent_subject_id_idx').on(t.subjectId) }),
);

// ---------------------------------------------------------------------------
// ndpr_dsr_requests — NDPA §34–38
// ---------------------------------------------------------------------------

export const dsrRequests = pgTable(
  'ndpr_dsr_requests',
  {
    id:              text('id').primaryKey().$defaultFn(() => createId()),
    type:            text('type').notNull(),
    status:          text('status').notNull().default('pending'),
    subjectName:     text('subject_name').notNull(),
    subjectEmail:    text('subject_email').notNull(),
    subjectPhone:    text('subject_phone'),
    identifierType:  text('identifier_type').notNull(),
    identifierValue: text('identifier_value').notNull(),
    description:     text('description'),
    internalNotes:   text('internal_notes'),
    assignedTo:      text('assigned_to'),
    submittedAt:     timestamp('submitted_at').defaultNow().notNull(),
    acknowledgedAt:  timestamp('acknowledged_at'),
    completedAt:     timestamp('completed_at'),
    dueAt:           timestamp('due_at').notNull(),
  },
  (t) => ({
    statusIdx:      index('dsr_status_idx').on(t.status),
    subjectEmailIdx: index('dsr_subject_email_idx').on(t.subjectEmail),
  }),
);

// ---------------------------------------------------------------------------
// ndpr_breach_reports — NDPA §40
// ---------------------------------------------------------------------------

export const breachReports = pgTable(
  'ndpr_breach_reports',
  {
    id:                   text('id').primaryKey().$defaultFn(() => createId()),
    title:                text('title').notNull(),
    description:          text('description').notNull(),
    category:             text('category').notNull(),
    severity:             text('severity').notNull(),
    status:               text('status').notNull().default('ongoing'),
    discoveredAt:         timestamp('discovered_at').notNull(),
    occurredAt:           timestamp('occurred_at'),
    reportedAt:           timestamp('reported_at').defaultNow().notNull(),
    ndpcNotifiedAt:       timestamp('ndpc_notified_at'),
    reporterName:         text('reporter_name').notNull(),
    reporterEmail:        text('reporter_email').notNull(),
    reporterDepartment:   text('reporter_department'),
    affectedSystems:      json('affected_systems').notNull(),
    dataTypes:            json('data_types').notNull(),
    estimatedAffected:    integer('estimated_affected'),
    initialActions:       text('initial_actions'),
    ndpcNotificationSent: boolean('ndpc_notification_sent').notNull().default(false),
  },
  (t) => ({
    statusIdx:   index('breach_status_idx').on(t.status),
    severityIdx: index('breach_severity_idx').on(t.severity),
  }),
);

// ---------------------------------------------------------------------------
// ndpr_processing_records — ROPA
// ---------------------------------------------------------------------------

export const processingRecords = pgTable('ndpr_processing_records', {
  id:                text('id').primaryKey().$defaultFn(() => createId()),
  purpose:           text('purpose').notNull(),
  lawfulBasis:       text('lawful_basis').notNull(),
  dataCategories:    json('data_categories').notNull(),
  dataSubjects:      json('data_subjects').notNull(),
  recipients:        json('recipients').notNull(),
  retentionPeriod:   text('retention_period').notNull(),
  securityMeasures:  json('security_measures').notNull(),
  transferCountries: json('transfer_countries'),
  transferMechanism: text('transfer_mechanism'),
  dpiaConducted:     boolean('dpia_conducted').notNull().default(false),
  status:            text('status').notNull().default('active'),
  createdAt:         timestamp('created_at').defaultNow().notNull(),
  updatedAt:         timestamp('updated_at').defaultNow().notNull(),
});

// ---------------------------------------------------------------------------
// ndpr_dpia_records — NDPA §34(3)
// ---------------------------------------------------------------------------

export const dpiaRecords = pgTable(
  'ndpr_dpia_records',
  {
    id:          text('id').primaryKey().$defaultFn(() => createId()),
    projectName: text('project_name').notNull(),
    description: text('description').notNull(),
    dpiaData:    json('dpia_data').notNull(),
    overallRisk: text('overall_risk').notNull(),
    score:       integer('score').notNull(),
    status:      text('status').notNull().default('draft'),
    conductedBy: text('conducted_by').notNull(),
    approvedBy:  text('approved_by'),
    createdAt:   timestamp('created_at').defaultNow().notNull(),
    updatedAt:   timestamp('updated_at').defaultNow().notNull(),
  },
  (t) => ({
    statusIdx:      index('dpia_status_idx').on(t.status),
    conductedByIdx: index('dpia_conducted_by_idx').on(t.conductedBy),
  }),
);

// ---------------------------------------------------------------------------
// ndpr_lawful_basis_records — NDPA §25
// ---------------------------------------------------------------------------

export const lawfulBasisRecords = pgTable(
  'ndpr_lawful_basis_records',
  {
    id:             text('id').primaryKey().$defaultFn(() => createId()),
    activityName:   text('activity_name').notNull(),
    lawfulBasis:    text('lawful_basis').notNull(),
    justification:  text('justification').notNull(),
    dataCategories: json('data_categories').notNull(),
    purposes:       json('purposes').notNull(),
    assessedBy:     text('assessed_by').notNull(),
    assessedAt:     timestamp('assessed_at').defaultNow().notNull(),
    reviewDate:     timestamp('review_date'),
    createdAt:      timestamp('created_at').defaultNow().notNull(),
    updatedAt:      timestamp('updated_at').defaultNow().notNull(),
  },
  (t) => ({
    lawfulBasisIdx: index('lawful_basis_idx').on(t.lawfulBasis),
    assessedByIdx:  index('lawful_basis_assessed_by_idx').on(t.assessedBy),
  }),
);

// ---------------------------------------------------------------------------
// ndpr_cross_border_transfer_records — NDPA §41–42
// ---------------------------------------------------------------------------

export const crossBorderTransferRecords = pgTable(
  'ndpr_cross_border_transfer_records',
  {
    id:                    text('id').primaryKey().$defaultFn(() => createId()),
    destinationCountry:    text('destination_country').notNull(),
    recipientName:         text('recipient_name').notNull(),
    transferMechanism:     text('transfer_mechanism').notNull(),
    safeguards:            text('safeguards').notNull(),
    dataCategories:        json('data_categories').notNull(),
    adequacyStatus:        text('adequacy_status').notNull(),
    ndpcApprovalRequired:  boolean('ndpc_approval_required').notNull().default(false),
    ndpcApprovalReference: text('ndpc_approval_reference'),
    riskLevel:             text('risk_level').notNull(),
    createdAt:             timestamp('created_at').defaultNow().notNull(),
    updatedAt:             timestamp('updated_at').defaultNow().notNull(),
  },
  (t) => ({
    destinationCountryIdx: index('cross_border_destination_idx').on(t.destinationCountry),
    riskLevelIdx:          index('cross_border_risk_level_idx').on(t.riskLevel),
  }),
);

// ---------------------------------------------------------------------------
// ndpr_audit_log — §44 accountability
// ---------------------------------------------------------------------------

export const auditLog = pgTable(
  'ndpr_audit_log',
  {
    id:          text('id').primaryKey().$defaultFn(() => createId()),
    module:      text('module').notNull(),
    action:      text('action').notNull(),
    entityId:    text('entity_id').notNull(),
    entityType:  text('entity_type').notNull(),
    changes:     json('changes'),
    performedBy: text('performed_by'),
    createdAt:   timestamp('created_at').defaultNow().notNull(),
  },
  (t) => ({
    moduleEntityIdx: index('audit_module_entity_idx').on(t.module, t.entityId),
  }),
);

// ---------------------------------------------------------------------------
// Inferred types
// ---------------------------------------------------------------------------

export type ConsentRecord    = typeof consentRecords.$inferSelect;
export type NewConsentRecord = typeof consentRecords.$inferInsert;
export type DSRRequest       = typeof dsrRequests.$inferSelect;
export type NewDSRRequest    = typeof dsrRequests.$inferInsert;
export type BreachReport     = typeof breachReports.$inferSelect;
export type NewBreachReport  = typeof breachReports.$inferInsert;
export type ProcessingRecord         = typeof processingRecords.$inferSelect;
export type DPIARecord               = typeof dpiaRecords.$inferSelect;
export type NewDPIARecord            = typeof dpiaRecords.$inferInsert;
export type LawfulBasisRecord        = typeof lawfulBasisRecords.$inferSelect;
export type NewLawfulBasisRecord     = typeof lawfulBasisRecords.$inferInsert;
export type CrossBorderTransfer      = typeof crossBorderTransferRecords.$inferSelect;
export type NewCrossBorderTransfer   = typeof crossBorderTransferRecords.$inferInsert;
export type AuditLogEntry            = typeof auditLog.$inferSelect;
