/**
 * Express — DPIA (Data Protection Impact Assessment) Router
 * Generated by create-ndpr for: {{ORG_NAME}}
 * DPO: {{DPO_EMAIL}}
 *
 * NDPA §34(3) — a DPIA must be conducted where processing is likely
 * to result in a high risk to the rights and freedoms of data subjects.
 *
 * Routes:
 *   GET    /dpia               — List DPIA records (optional ?status= filter)
 *   GET    /dpia/:id           — Get a single DPIA record
 *   POST   /dpia               — Create a new DPIA record
 *   PUT    /dpia/:id           — Update an existing DPIA record
 *   DELETE /dpia/:id           — Delete a DPIA record
 *
 * Usage:
 *   import { dpiaRouter } from './routes/dpia';
 *   app.use('/api/dpia', dpiaRouter);
 */

import { Router } from 'express';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
export const dpiaRouter = Router();

// GET /dpia?status=draft
dpiaRouter.get('/', async (req, res) => {
  const { status } = req.query;

  const records = await prisma.dPIARecord.findMany({
    where: status && typeof status === 'string' ? { status } : undefined,
    orderBy: { createdAt: 'desc' },
  });

  return res.json(records);
});

// GET /dpia/:id
dpiaRouter.get('/:id', async (req, res) => {
  const record = await prisma.dPIARecord.findUnique({ where: { id: req.params.id } });

  if (!record) {
    return res.status(404).json({ error: 'DPIA record not found' });
  }

  return res.json(record);
});

// POST /dpia
dpiaRouter.post('/', async (req, res) => {
  const {
    projectName,
    description,
    dpiaData,
    overallRisk,
    score,
    conductedBy,
    approvedBy,
  } = req.body;

  if (!projectName || !description || !dpiaData || !overallRisk || score == null || !conductedBy) {
    return res.status(400).json({
      error: 'projectName, description, dpiaData, overallRisk, score, and conductedBy are required',
    });
  }

  const record = await prisma.dPIARecord.create({
    data: {
      projectName,
      description,
      dpiaData,
      overallRisk,
      score,
      status: 'draft',
      conductedBy,
      approvedBy: approvedBy ?? null,
    },
  });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'dpia',
      action: 'created',
      entityId: record.id,
      entityType: 'DPIARecord',
      changes: { projectName, overallRisk, score, status: 'draft' },
    },
  });

  return res.status(201).json(record);
});

// PUT /dpia/:id
dpiaRouter.put('/:id', async (req, res) => {
  const { id } = req.params;

  const existing = await prisma.dPIARecord.findUnique({ where: { id } });
  if (!existing) {
    return res.status(404).json({ error: 'DPIA record not found' });
  }

  const record = await prisma.dPIARecord.update({
    where: { id },
    data: req.body,
  });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'dpia',
      action: 'updated',
      entityId: record.id,
      entityType: 'DPIARecord',
      changes: req.body,
    },
  });

  return res.json(record);
});

// DELETE /dpia/:id
dpiaRouter.delete('/:id', async (req, res) => {
  const { id } = req.params;

  const existing = await prisma.dPIARecord.findUnique({ where: { id } });
  if (!existing) {
    return res.status(404).json({ error: 'DPIA record not found' });
  }

  await prisma.dPIARecord.delete({ where: { id } });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'dpia',
      action: 'deleted',
      entityId: id,
      entityType: 'DPIARecord',
      changes: { projectName: existing.projectName },
    },
  });

  return res.json({ success: true });
});
