/**
 * Express — Consent Router
 * Generated by create-ndpr for: {{ORG_NAME}}
 * DPO: {{DPO_EMAIL}}
 *
 * NDPA §25 (lawful basis) and §26 (right to withdraw consent).
 *
 * Routes:
 *   GET    /consent?subjectId=xxx  — Load the active consent record
 *   POST   /consent                — Save new consent (revokes previous)
 *   DELETE /consent?subjectId=xxx  — Revoke all active consent
 *
 * Usage:
 *   import { consentRouter } from './routes/consent';
 *   app.use('/api/consent', consentRouter);
 */

import { Router } from 'express';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
export const consentRouter = Router();

// GET /consent?subjectId=xxx
consentRouter.get('/', async (req, res) => {
  const { subjectId } = req.query;

  if (!subjectId || typeof subjectId !== 'string') {
    return res.status(400).json({ error: 'subjectId required' });
  }

  const record = await prisma.consentRecord.findFirst({
    where: { subjectId, revokedAt: null },
    orderBy: { createdAt: 'desc' },
  });

  return res.json(record);
});

// POST /consent
consentRouter.post('/', async (req, res) => {
  const { subjectId, consents, version, method, lawfulBasis } = req.body;

  if (!subjectId || !consents || !version) {
    return res.status(400).json({ error: 'subjectId, consents, and version are required' });
  }

  // Revoke any previously active records (immutable-audit pattern — NDPA §44).
  await prisma.consentRecord.updateMany({
    where: { subjectId, revokedAt: null },
    data: { revokedAt: new Date() },
  });

  const record = await prisma.consentRecord.create({
    data: {
      subjectId,
      consents,
      version,
      method: method ?? 'api',
      lawfulBasis: lawfulBasis ?? null,
      ipAddress:
        (req.headers['x-forwarded-for'] as string)?.split(',')[0].trim() ??
        req.socket.remoteAddress ??
        null,
      userAgent: req.headers['user-agent'] ?? null,
    },
  });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'consent',
      action: 'created',
      entityId: record.id,
      entityType: 'ConsentRecord',
      changes: { subjectId, version, consents },
    },
  });

  return res.status(201).json(record);
});

// DELETE /consent?subjectId=xxx
consentRouter.delete('/', async (req, res) => {
  const { subjectId } = req.query;

  if (!subjectId || typeof subjectId !== 'string') {
    return res.status(400).json({ error: 'subjectId required' });
  }

  await prisma.consentRecord.updateMany({
    where: { subjectId, revokedAt: null },
    data: { revokedAt: new Date() },
  });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'consent',
      action: 'revoked',
      entityId: subjectId,
      entityType: 'ConsentRecord',
    },
  });

  return res.json({ success: true });
});
