/**
 * Express — Cross-Border Transfer Router
 * Generated by create-ndpr for: {{ORG_NAME}}
 * DPO: {{DPO_EMAIL}}
 *
 * NDPA §41–42 — transfers of personal data outside Nigeria require
 * adequate safeguards and, in some cases, NDPC approval.
 *
 * Routes:
 *   GET    /cross-border               — List transfers (optional ?riskLevel= or ?destinationCountry= filter)
 *   GET    /cross-border/:id           — Get a single transfer record
 *   POST   /cross-border               — Register a new cross-border transfer
 *   PUT    /cross-border/:id           — Update an existing transfer record
 *   DELETE /cross-border/:id           — Delete a transfer record
 *
 * Usage:
 *   import { crossBorderRouter } from './routes/cross-border';
 *   app.use('/api/cross-border', crossBorderRouter);
 */

import { Router } from 'express';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
export const crossBorderRouter = Router();

// GET /cross-border?riskLevel=high&destinationCountry=US
crossBorderRouter.get('/', async (req, res) => {
  const { riskLevel, destinationCountry } = req.query;

  const where: Record<string, string> = {};
  if (riskLevel && typeof riskLevel === 'string') where.riskLevel = riskLevel;
  if (destinationCountry && typeof destinationCountry === 'string') where.destinationCountry = destinationCountry;

  const records = await prisma.crossBorderTransferRecord.findMany({
    where: Object.keys(where).length > 0 ? where : undefined,
    orderBy: { createdAt: 'desc' },
  });

  return res.json(records);
});

// GET /cross-border/:id
crossBorderRouter.get('/:id', async (req, res) => {
  const record = await prisma.crossBorderTransferRecord.findUnique({ where: { id: req.params.id } });

  if (!record) {
    return res.status(404).json({ error: 'Cross-border transfer record not found' });
  }

  return res.json(record);
});

// POST /cross-border
crossBorderRouter.post('/', async (req, res) => {
  const {
    destinationCountry,
    recipientName,
    transferMechanism,
    safeguards,
    dataCategories,
    adequacyStatus,
    ndpcApprovalRequired,
    ndpcApprovalReference,
    riskLevel,
  } = req.body;

  if (
    !destinationCountry ||
    !recipientName ||
    !transferMechanism ||
    !safeguards ||
    !dataCategories ||
    !adequacyStatus ||
    !riskLevel
  ) {
    return res.status(400).json({
      error:
        'destinationCountry, recipientName, transferMechanism, safeguards, dataCategories, adequacyStatus, and riskLevel are required',
    });
  }

  if (!Array.isArray(dataCategories)) {
    return res.status(400).json({ error: 'dataCategories must be an array' });
  }

  const record = await prisma.crossBorderTransferRecord.create({
    data: {
      destinationCountry,
      recipientName,
      transferMechanism,
      safeguards,
      dataCategories,
      adequacyStatus,
      ndpcApprovalRequired: ndpcApprovalRequired ?? false,
      ndpcApprovalReference: ndpcApprovalReference ?? null,
      riskLevel,
    },
  });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'cross-border',
      action: 'created',
      entityId: record.id,
      entityType: 'CrossBorderTransferRecord',
      changes: { destinationCountry, recipientName, riskLevel },
    },
  });

  return res.status(201).json(record);
});

// PUT /cross-border/:id
crossBorderRouter.put('/:id', async (req, res) => {
  const { id } = req.params;

  const existing = await prisma.crossBorderTransferRecord.findUnique({ where: { id } });
  if (!existing) {
    return res.status(404).json({ error: 'Cross-border transfer record not found' });
  }

  const record = await prisma.crossBorderTransferRecord.update({
    where: { id },
    data: req.body,
  });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'cross-border',
      action: 'updated',
      entityId: record.id,
      entityType: 'CrossBorderTransferRecord',
      changes: req.body,
    },
  });

  return res.json(record);
});

// DELETE /cross-border/:id
crossBorderRouter.delete('/:id', async (req, res) => {
  const { id } = req.params;

  const existing = await prisma.crossBorderTransferRecord.findUnique({ where: { id } });
  if (!existing) {
    return res.status(404).json({ error: 'Cross-border transfer record not found' });
  }

  await prisma.crossBorderTransferRecord.delete({ where: { id } });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'cross-border',
      action: 'deleted',
      entityId: id,
      entityType: 'CrossBorderTransferRecord',
      changes: { destinationCountry: existing.destinationCountry, recipientName: existing.recipientName },
    },
  });

  return res.json({ success: true });
});
