/**
 * Express — NDPR Compliance Router
 * Generated by create-ndpr for: {{ORG_NAME}}
 * DPO: {{DPO_EMAIL}}
 *
 * Mount this router in your Express app:
 *
 *   import express from 'express';
 *   import cookieParser from 'cookie-parser';
 *   import { createNDPRRouter } from './src/ndpr';
 *
 *   const app = express();
 *   app.use(express.json());
 *   app.use(cookieParser());
 *   app.use('/api/ndpr', createNDPRRouter());
 *
 * Routes exposed:
 *   GET/POST/DELETE  /api/ndpr/consent   — NDPA §25–26
 *   GET/POST         /api/ndpr/dsr       — NDPA §34–38
 *   GET/POST         /api/ndpr/breach    — NDPA §40
 */

import { Router } from 'express';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// ---------------------------------------------------------------------------
// Consent router — NDPA §25–26
// ---------------------------------------------------------------------------

function consentRouter(): Router {
  const router = Router();

  // GET /consent?subjectId=xxx
  router.get('/', async (req, res) => {
    const { subjectId } = req.query;
    if (!subjectId || typeof subjectId !== 'string') {
      return res.status(400).json({ error: 'subjectId required' });
    }
    const record = await prisma.consentRecord.findFirst({
      where: { subjectId, revokedAt: null },
      orderBy: { createdAt: 'desc' },
    });
    return res.json(record);
  });

  // POST /consent
  router.post('/', async (req, res) => {
    const { subjectId, consents, version, method, lawfulBasis } = req.body;
    if (!subjectId || !consents || !version) {
      return res.status(400).json({ error: 'subjectId, consents, and version are required' });
    }
    await prisma.consentRecord.updateMany({
      where: { subjectId, revokedAt: null },
      data: { revokedAt: new Date() },
    });
    const record = await prisma.consentRecord.create({
      data: {
        subjectId,
        consents,
        version,
        method: method ?? 'api',
        lawfulBasis: lawfulBasis ?? null,
        ipAddress:
          (req.headers['x-forwarded-for'] as string)?.split(',')[0].trim() ??
          req.socket.remoteAddress ??
          null,
        userAgent: req.headers['user-agent'] ?? null,
      },
    });
    await prisma.complianceAuditLog.create({
      data: {
        module: 'consent',
        action: 'created',
        entityId: record.id,
        entityType: 'ConsentRecord',
        changes: { subjectId, version, consents },
      },
    });
    return res.status(201).json(record);
  });

  // DELETE /consent?subjectId=xxx
  router.delete('/', async (req, res) => {
    const { subjectId } = req.query;
    if (!subjectId || typeof subjectId !== 'string') {
      return res.status(400).json({ error: 'subjectId required' });
    }
    await prisma.consentRecord.updateMany({
      where: { subjectId, revokedAt: null },
      data: { revokedAt: new Date() },
    });
    await prisma.complianceAuditLog.create({
      data: {
        module: 'consent',
        action: 'revoked',
        entityId: subjectId,
        entityType: 'ConsentRecord',
      },
    });
    return res.json({ success: true });
  });

  return router;
}

// ---------------------------------------------------------------------------
// DSR router — NDPA §34–38
// ---------------------------------------------------------------------------

function dsrRouter(): Router {
  const router = Router();

  // GET /dsr?status=pending
  router.get('/', async (req, res) => {
    const { status } = req.query;
    const requests = await prisma.dSRRequest.findMany({
      where: status && typeof status === 'string' ? { status } : undefined,
      orderBy: { submittedAt: 'desc' },
    });
    return res.json(requests);
  });

  // POST /dsr
  router.post('/', async (req, res) => {
    const { type, subjectName, subjectEmail, subjectPhone, identifierType, identifierValue, description } =
      req.body;
    if (!type || !subjectName || !subjectEmail || !identifierType || !identifierValue) {
      return res
        .status(400)
        .json({ error: 'type, subjectName, subjectEmail, identifierType, and identifierValue are required' });
    }
    const dueAt = new Date();
    dueAt.setDate(dueAt.getDate() + 30);
    const request = await prisma.dSRRequest.create({
      data: {
        type,
        subjectName,
        subjectEmail,
        subjectPhone: subjectPhone ?? null,
        identifierType,
        identifierValue,
        description: description ?? null,
        status: 'pending',
        dueAt,
      },
    });
    await prisma.complianceAuditLog.create({
      data: {
        module: 'dsr',
        action: 'submitted',
        entityId: request.id,
        entityType: 'DSRRequest',
        changes: { type, subjectEmail, status: 'pending' },
      },
    });
    return res.status(201).json(request);
  });

  return router;
}

// ---------------------------------------------------------------------------
// Breach router — NDPA §40
// ---------------------------------------------------------------------------

function breachRouter(): Router {
  const router = Router();

  function calculateSeverity(category: string, estimatedAffected?: number) {
    const highRisk = ['unauthorized_access', 'ransomware', 'data_exfiltration', 'identity_theft'];
    if (highRisk.includes(category)) return (estimatedAffected ?? 0) > 1000 ? 'critical' : 'high';
    if ((estimatedAffected ?? 0) > 500) return 'high';
    if ((estimatedAffected ?? 0) > 50) return 'medium';
    return 'low';
  }

  // GET /breach?status=ongoing
  router.get('/', async (req, res) => {
    const { status } = req.query;
    const reports = await prisma.breachReport.findMany({
      where: status && typeof status === 'string' ? { status } : undefined,
      orderBy: { reportedAt: 'desc' },
    });
    return res.json(reports);
  });

  // POST /breach
  router.post('/', async (req, res) => {
    const {
      title, description, category, discoveredAt, occurredAt,
      reporterName, reporterEmail, reporterDepartment,
      affectedSystems, dataTypes, estimatedAffected, initialActions,
    } = req.body;

    if (!title || !description || !category || !discoveredAt || !reporterName || !reporterEmail) {
      return res.status(400).json({
        error: 'title, description, category, discoveredAt, reporterName, and reporterEmail are required',
      });
    }
    if (!Array.isArray(affectedSystems) || !Array.isArray(dataTypes)) {
      return res.status(400).json({ error: 'affectedSystems and dataTypes must be arrays' });
    }

    const severity = calculateSeverity(category, estimatedAffected);
    const report = await prisma.breachReport.create({
      data: {
        title, description, category, severity, status: 'ongoing',
        discoveredAt: new Date(discoveredAt),
        occurredAt: occurredAt ? new Date(occurredAt) : null,
        reporterName, reporterEmail,
        reporterDepartment: reporterDepartment ?? null,
        affectedSystems, dataTypes,
        estimatedAffected: estimatedAffected ?? null,
        initialActions: initialActions ?? null,
      },
    });
    await prisma.complianceAuditLog.create({
      data: {
        module: 'breach',
        action: 'reported',
        entityId: report.id,
        entityType: 'BreachReport',
        changes: { title, category, severity, status: 'ongoing' },
      },
    });
    return res.status(201).json(report);
  });

  return router;
}

// ---------------------------------------------------------------------------
// Main factory
// ---------------------------------------------------------------------------

/**
 * Returns a fully configured NDPR compliance Express Router.
 *
 * Mount with:
 *   app.use('/api/ndpr', createNDPRRouter());
 */
export function createNDPRRouter(): Router {
  const router = Router();
  router.use('/consent', consentRouter());
  router.use('/dsr', dsrRouter());
  router.use('/breach', breachRouter());
  return router;
}
