/**
 * Express — DPIA (Data Protection Impact Assessment) Router
 * Generated by create-ndpr for: {{ORG_NAME}}
 * DPO: {{DPO_EMAIL}}
 *
 * NDPA §28 — a DPIA must be conducted where processing is likely
 * to result in a high risk to the rights and freedoms of data subjects.
 *
 * Routes:
 *   GET    /dpia               — List DPIA records (optional ?status= filter)
 *   GET    /dpia/:id           — Get a single DPIA record
 *   POST   /dpia               — Create a new DPIA record
 *   PUT    /dpia/:id           — Update an existing DPIA record
 *   DELETE /dpia/:id           — Delete a DPIA record
 *
 * Usage:
 *   import { dpiaRouter } from './routes/dpia';
 *   app.use('/api/dpia', dpiaRouter);
 */

import { Router } from 'express';
// {{#if ORM=prisma}}
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
// {{/if}}
// {{#if ORM=drizzle}}
import { db } from '@/drizzle';
import { dpiaRecords, complianceAuditLog } from '@/drizzle/ndpr-schema';
import { eq, desc } from 'drizzle-orm';
// {{/if}}
// {{#if ORM=none}}
// TODO ({{ORG_NAME}}): wire this to your persistent store of choice. The
// in-memory map below is enough to develop against locally but DOES NOT
// satisfy NDPA Section 44 (record-keeping). Replace `dpiaStore`/`auditLog`
// with your DB / KV / API.
interface DPIARecord {
  id: string;
  projectName: string;
  description: string;
  dpiaData: unknown;
  overallRisk: string;
  score: number;
  status: string;
  conductedBy: string;
  approvedBy: string | null;
  createdAt: Date;
  updatedAt: Date;
}
const dpiaStore = new Map<string, DPIARecord>();
const auditLog: Array<{ id: string; module: string; action: string; entityId: string; at: Date }> = [];
function newId() { return crypto.randomUUID(); }
// {{/if}}

export const dpiaRouter = Router();

// GET /dpia?status=draft
dpiaRouter.get('/', async (req, res) => {
  const { status } = req.query;
  const statusFilter = typeof status === 'string' ? status : undefined;

  // {{#if ORM=prisma}}
  const records = await prisma.dPIARecord.findMany({
    where: statusFilter ? { status: statusFilter } : undefined,
    orderBy: { createdAt: 'desc' },
  });
  // {{/if}}
  // {{#if ORM=drizzle}}
  const records = statusFilter
    ? await db.select().from(dpiaRecords).where(eq(dpiaRecords.status, statusFilter)).orderBy(desc(dpiaRecords.createdAt))
    : await db.select().from(dpiaRecords).orderBy(desc(dpiaRecords.createdAt));
  // {{/if}}
  // {{#if ORM=none}}
  const records = [...dpiaStore.values()]
    .filter((r) => (statusFilter ? r.status === statusFilter : true))
    .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
  // {{/if}}

  return res.json(records);
});

// GET /dpia/:id
dpiaRouter.get('/:id', async (req, res) => {
  // {{#if ORM=prisma}}
  const record = await prisma.dPIARecord.findUnique({ where: { id: req.params.id } });
  // {{/if}}
  // {{#if ORM=drizzle}}
  const [record] = await db.select().from(dpiaRecords).where(eq(dpiaRecords.id, req.params.id)).limit(1);
  // {{/if}}
  // {{#if ORM=none}}
  const record = dpiaStore.get(req.params.id) ?? null;
  // {{/if}}

  if (!record) {
    return res.status(404).json({ error: 'DPIA record not found' });
  }

  return res.json(record);
});

// POST /dpia
dpiaRouter.post('/', async (req, res) => {
  const {
    projectName,
    description,
    dpiaData,
    overallRisk,
    score,
    conductedBy,
    approvedBy,
  } = req.body;

  if (!projectName || !description || !dpiaData || !overallRisk || score == null || !conductedBy) {
    return res.status(400).json({
      error: 'projectName, description, dpiaData, overallRisk, score, and conductedBy are required',
    });
  }

  // {{#if ORM=prisma}}
  const record = await prisma.dPIARecord.create({
    data: {
      projectName,
      description,
      dpiaData,
      overallRisk,
      score,
      status: 'draft',
      conductedBy,
      approvedBy: approvedBy ?? null,
    },
  });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'dpia',
      action: 'created',
      entityId: record.id,
      entityType: 'DPIARecord',
      changes: { projectName, overallRisk, score, status: 'draft' },
    },
  });
  // {{/if}}
  // {{#if ORM=drizzle}}
  const [record] = await db.insert(dpiaRecords).values({
    projectName,
    description,
    dpiaData,
    overallRisk,
    score,
    status: 'draft',
    conductedBy,
    approvedBy: approvedBy ?? null,
  }).returning();

  await db.insert(complianceAuditLog).values({
    module: 'dpia',
    action: 'created',
    entityId: record.id,
    entityType: 'DPIARecord',
    changes: { projectName, overallRisk, score, status: 'draft' },
  });
  // {{/if}}
  // {{#if ORM=none}}
  const now = new Date();
  const record: DPIARecord = {
    id: newId(),
    projectName,
    description,
    dpiaData,
    overallRisk,
    score,
    status: 'draft',
    conductedBy,
    approvedBy: approvedBy ?? null,
    createdAt: now,
    updatedAt: now,
  };
  dpiaStore.set(record.id, record);
  auditLog.push({ id: newId(), module: 'dpia', action: 'created', entityId: record.id, at: new Date() });
  // {{/if}}

  return res.status(201).json(record);
});

// PUT /dpia/:id
dpiaRouter.put('/:id', async (req, res) => {
  const { id } = req.params;

  // {{#if ORM=prisma}}
  const existing = await prisma.dPIARecord.findUnique({ where: { id } });
  if (!existing) {
    return res.status(404).json({ error: 'DPIA record not found' });
  }

  const record = await prisma.dPIARecord.update({
    where: { id },
    data: req.body,
  });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'dpia',
      action: 'updated',
      entityId: record.id,
      entityType: 'DPIARecord',
      changes: req.body,
    },
  });
  // {{/if}}
  // {{#if ORM=drizzle}}
  const [existing] = await db.select().from(dpiaRecords).where(eq(dpiaRecords.id, id)).limit(1);
  if (!existing) {
    return res.status(404).json({ error: 'DPIA record not found' });
  }

  const [record] = await db.update(dpiaRecords).set(req.body).where(eq(dpiaRecords.id, id)).returning();

  await db.insert(complianceAuditLog).values({
    module: 'dpia',
    action: 'updated',
    entityId: record.id,
    entityType: 'DPIARecord',
    changes: req.body,
  });
  // {{/if}}
  // {{#if ORM=none}}
  const existing = dpiaStore.get(id);
  if (!existing) {
    return res.status(404).json({ error: 'DPIA record not found' });
  }
  const record: DPIARecord = { ...existing, ...req.body, id, updatedAt: new Date() };
  dpiaStore.set(id, record);
  auditLog.push({ id: newId(), module: 'dpia', action: 'updated', entityId: record.id, at: new Date() });
  // {{/if}}

  return res.json(record);
});

// DELETE /dpia/:id
dpiaRouter.delete('/:id', async (req, res) => {
  const { id } = req.params;

  // {{#if ORM=prisma}}
  const existing = await prisma.dPIARecord.findUnique({ where: { id } });
  if (!existing) {
    return res.status(404).json({ error: 'DPIA record not found' });
  }

  await prisma.dPIARecord.delete({ where: { id } });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'dpia',
      action: 'deleted',
      entityId: id,
      entityType: 'DPIARecord',
      changes: { projectName: existing.projectName },
    },
  });
  // {{/if}}
  // {{#if ORM=drizzle}}
  const [existing] = await db.select().from(dpiaRecords).where(eq(dpiaRecords.id, id)).limit(1);
  if (!existing) {
    return res.status(404).json({ error: 'DPIA record not found' });
  }

  await db.delete(dpiaRecords).where(eq(dpiaRecords.id, id));

  await db.insert(complianceAuditLog).values({
    module: 'dpia',
    action: 'deleted',
    entityId: id,
    entityType: 'DPIARecord',
    changes: { projectName: existing.projectName },
  });
  // {{/if}}
  // {{#if ORM=none}}
  const existing = dpiaStore.get(id);
  if (!existing) {
    return res.status(404).json({ error: 'DPIA record not found' });
  }
  dpiaStore.delete(id);
  auditLog.push({ id: newId(), module: 'dpia', action: 'deleted', entityId: id, at: new Date() });
  // {{/if}}

  return res.json({ success: true });
});
