/**
 * Express — Lawful Basis Router
 * Generated by create-ndpr for: {{ORG_NAME}}
 * DPO: {{DPO_EMAIL}}
 *
 * NDPA §25 — data processing must have a lawful basis. This router
 * manages a register of processing activities and their lawful bases.
 *
 * Routes:
 *   GET    /lawful-basis               — List records (optional ?lawfulBasis= filter)
 *   GET    /lawful-basis/:id           — Get a single record
 *   POST   /lawful-basis               — Create a new lawful basis record
 *   PUT    /lawful-basis/:id           — Update an existing record
 *   DELETE /lawful-basis/:id           — Delete a record
 *
 * Usage:
 *   import { lawfulBasisRouter } from './routes/lawful-basis';
 *   app.use('/api/lawful-basis', lawfulBasisRouter);
 */

import { Router } from 'express';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
export const lawfulBasisRouter = Router();

// GET /lawful-basis?lawfulBasis=consent
lawfulBasisRouter.get('/', async (req, res) => {
  const { lawfulBasis } = req.query;

  const records = await prisma.lawfulBasisRecord.findMany({
    where: lawfulBasis && typeof lawfulBasis === 'string' ? { lawfulBasis } : undefined,
    orderBy: { createdAt: 'desc' },
  });

  return res.json(records);
});

// GET /lawful-basis/:id
lawfulBasisRouter.get('/:id', async (req, res) => {
  const record = await prisma.lawfulBasisRecord.findUnique({ where: { id: req.params.id } });

  if (!record) {
    return res.status(404).json({ error: 'Lawful basis record not found' });
  }

  return res.json(record);
});

// POST /lawful-basis
lawfulBasisRouter.post('/', async (req, res) => {
  const {
    activityName,
    lawfulBasis,
    justification,
    dataCategories,
    purposes,
    assessedBy,
    reviewDate,
  } = req.body;

  if (!activityName || !lawfulBasis || !justification || !dataCategories || !purposes || !assessedBy) {
    return res.status(400).json({
      error: 'activityName, lawfulBasis, justification, dataCategories, purposes, and assessedBy are required',
    });
  }

  if (!Array.isArray(dataCategories) || !Array.isArray(purposes)) {
    return res.status(400).json({ error: 'dataCategories and purposes must be arrays' });
  }

  const record = await prisma.lawfulBasisRecord.create({
    data: {
      activityName,
      lawfulBasis,
      justification,
      dataCategories,
      purposes,
      assessedBy,
      reviewDate: reviewDate ? new Date(reviewDate) : null,
    },
  });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'lawful-basis',
      action: 'created',
      entityId: record.id,
      entityType: 'LawfulBasisRecord',
      changes: { activityName, lawfulBasis, assessedBy },
    },
  });

  return res.status(201).json(record);
});

// PUT /lawful-basis/:id
lawfulBasisRouter.put('/:id', async (req, res) => {
  const { id } = req.params;

  const existing = await prisma.lawfulBasisRecord.findUnique({ where: { id } });
  if (!existing) {
    return res.status(404).json({ error: 'Lawful basis record not found' });
  }

  const data = { ...req.body };
  if (data.reviewDate) {
    data.reviewDate = new Date(data.reviewDate);
  }

  const record = await prisma.lawfulBasisRecord.update({
    where: { id },
    data,
  });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'lawful-basis',
      action: 'updated',
      entityId: record.id,
      entityType: 'LawfulBasisRecord',
      changes: data,
    },
  });

  return res.json(record);
});

// DELETE /lawful-basis/:id
lawfulBasisRouter.delete('/:id', async (req, res) => {
  const { id } = req.params;

  const existing = await prisma.lawfulBasisRecord.findUnique({ where: { id } });
  if (!existing) {
    return res.status(404).json({ error: 'Lawful basis record not found' });
  }

  await prisma.lawfulBasisRecord.delete({ where: { id } });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'lawful-basis',
      action: 'deleted',
      entityId: id,
      entityType: 'LawfulBasisRecord',
      changes: { activityName: existing.activityName },
    },
  });

  return res.json({ success: true });
});
