/**
 * Express — Lawful Basis Router
 * Generated by create-ndpr for: {{ORG_NAME}}
 * DPO: {{DPO_EMAIL}}
 *
 * NDPA §25 — data processing must have a lawful basis. This router
 * manages a register of processing activities and their lawful bases.
 *
 * Routes:
 *   GET    /lawful-basis               — List records (optional ?lawfulBasis= filter)
 *   GET    /lawful-basis/:id           — Get a single record
 *   POST   /lawful-basis               — Create a new lawful basis record
 *   PUT    /lawful-basis/:id           — Update an existing record
 *   DELETE /lawful-basis/:id           — Delete a record
 *
 * Usage:
 *   import { lawfulBasisRouter } from './routes/lawful-basis';
 *   app.use('/api/lawful-basis', lawfulBasisRouter);
 */

import { Router } from 'express';
// {{#if ORM=prisma}}
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
// {{/if}}
// {{#if ORM=drizzle}}
import { db } from '@/drizzle';
import { lawfulBasisRecords, complianceAuditLog } from '@/drizzle/ndpr-schema';
import { eq, desc } from 'drizzle-orm';
// {{/if}}
// {{#if ORM=none}}
// TODO ({{ORG_NAME}}): wire this to your persistent store of choice. The
// in-memory map below is enough to develop against locally but DOES NOT
// satisfy NDPA Section 44 (record-keeping). Replace `lawfulBasisStore`/
// `auditLog` with your DB / KV / API.
interface LawfulBasisRecord {
  id: string;
  activityName: string;
  lawfulBasis: string;
  justification: string;
  dataCategories: string[];
  purposes: string[];
  assessedBy: string;
  reviewDate: Date | null;
  createdAt: Date;
  updatedAt: Date;
}
const lawfulBasisStore = new Map<string, LawfulBasisRecord>();
const auditLog: Array<{ id: string; module: string; action: string; entityId: string; at: Date }> = [];
function newId() { return crypto.randomUUID(); }
// {{/if}}

export const lawfulBasisRouter = Router();

// GET /lawful-basis?lawfulBasis=consent
lawfulBasisRouter.get('/', async (req, res) => {
  const { lawfulBasis } = req.query;
  const basisFilter = typeof lawfulBasis === 'string' ? lawfulBasis : undefined;

  // {{#if ORM=prisma}}
  const records = await prisma.lawfulBasisRecord.findMany({
    where: basisFilter ? { lawfulBasis: basisFilter } : undefined,
    orderBy: { createdAt: 'desc' },
  });
  // {{/if}}
  // {{#if ORM=drizzle}}
  const records = basisFilter
    ? await db.select().from(lawfulBasisRecords).where(eq(lawfulBasisRecords.lawfulBasis, basisFilter)).orderBy(desc(lawfulBasisRecords.createdAt))
    : await db.select().from(lawfulBasisRecords).orderBy(desc(lawfulBasisRecords.createdAt));
  // {{/if}}
  // {{#if ORM=none}}
  const records = [...lawfulBasisStore.values()]
    .filter((r) => (basisFilter ? r.lawfulBasis === basisFilter : true))
    .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
  // {{/if}}

  return res.json(records);
});

// GET /lawful-basis/:id
lawfulBasisRouter.get('/:id', async (req, res) => {
  // {{#if ORM=prisma}}
  const record = await prisma.lawfulBasisRecord.findUnique({ where: { id: req.params.id } });
  // {{/if}}
  // {{#if ORM=drizzle}}
  const [record] = await db.select().from(lawfulBasisRecords).where(eq(lawfulBasisRecords.id, req.params.id)).limit(1);
  // {{/if}}
  // {{#if ORM=none}}
  const record = lawfulBasisStore.get(req.params.id) ?? null;
  // {{/if}}

  if (!record) {
    return res.status(404).json({ error: 'Lawful basis record not found' });
  }

  return res.json(record);
});

// POST /lawful-basis
lawfulBasisRouter.post('/', async (req, res) => {
  const {
    activityName,
    lawfulBasis,
    justification,
    dataCategories,
    purposes,
    assessedBy,
    reviewDate,
  } = req.body;

  if (!activityName || !lawfulBasis || !justification || !dataCategories || !purposes || !assessedBy) {
    return res.status(400).json({
      error: 'activityName, lawfulBasis, justification, dataCategories, purposes, and assessedBy are required',
    });
  }

  if (!Array.isArray(dataCategories) || !Array.isArray(purposes)) {
    return res.status(400).json({ error: 'dataCategories and purposes must be arrays' });
  }

  // {{#if ORM=prisma}}
  const record = await prisma.lawfulBasisRecord.create({
    data: {
      activityName,
      lawfulBasis,
      justification,
      dataCategories,
      purposes,
      assessedBy,
      reviewDate: reviewDate ? new Date(reviewDate) : null,
    },
  });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'lawful-basis',
      action: 'created',
      entityId: record.id,
      entityType: 'LawfulBasisRecord',
      changes: { activityName, lawfulBasis, assessedBy },
    },
  });
  // {{/if}}
  // {{#if ORM=drizzle}}
  const [record] = await db.insert(lawfulBasisRecords).values({
    activityName,
    lawfulBasis,
    justification,
    dataCategories,
    purposes,
    assessedBy,
    reviewDate: reviewDate ? new Date(reviewDate) : null,
  }).returning();

  await db.insert(complianceAuditLog).values({
    module: 'lawful-basis',
    action: 'created',
    entityId: record.id,
    entityType: 'LawfulBasisRecord',
    changes: { activityName, lawfulBasis, assessedBy },
  });
  // {{/if}}
  // {{#if ORM=none}}
  const now = new Date();
  const record: LawfulBasisRecord = {
    id: newId(),
    activityName,
    lawfulBasis,
    justification,
    dataCategories,
    purposes,
    assessedBy,
    reviewDate: reviewDate ? new Date(reviewDate) : null,
    createdAt: now,
    updatedAt: now,
  };
  lawfulBasisStore.set(record.id, record);
  auditLog.push({ id: newId(), module: 'lawful-basis', action: 'created', entityId: record.id, at: new Date() });
  // {{/if}}

  return res.status(201).json(record);
});

// PUT /lawful-basis/:id
lawfulBasisRouter.put('/:id', async (req, res) => {
  const { id } = req.params;

  const data = { ...req.body };
  if (data.reviewDate) {
    data.reviewDate = new Date(data.reviewDate);
  }

  // {{#if ORM=prisma}}
  const existing = await prisma.lawfulBasisRecord.findUnique({ where: { id } });
  if (!existing) {
    return res.status(404).json({ error: 'Lawful basis record not found' });
  }

  const record = await prisma.lawfulBasisRecord.update({
    where: { id },
    data,
  });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'lawful-basis',
      action: 'updated',
      entityId: record.id,
      entityType: 'LawfulBasisRecord',
      changes: data,
    },
  });
  // {{/if}}
  // {{#if ORM=drizzle}}
  const [existing] = await db.select().from(lawfulBasisRecords).where(eq(lawfulBasisRecords.id, id)).limit(1);
  if (!existing) {
    return res.status(404).json({ error: 'Lawful basis record not found' });
  }

  const [record] = await db.update(lawfulBasisRecords).set(data).where(eq(lawfulBasisRecords.id, id)).returning();

  await db.insert(complianceAuditLog).values({
    module: 'lawful-basis',
    action: 'updated',
    entityId: record.id,
    entityType: 'LawfulBasisRecord',
    changes: data,
  });
  // {{/if}}
  // {{#if ORM=none}}
  const existing = lawfulBasisStore.get(id);
  if (!existing) {
    return res.status(404).json({ error: 'Lawful basis record not found' });
  }
  const record: LawfulBasisRecord = { ...existing, ...data, id, updatedAt: new Date() };
  lawfulBasisStore.set(id, record);
  auditLog.push({ id: newId(), module: 'lawful-basis', action: 'updated', entityId: record.id, at: new Date() });
  // {{/if}}

  return res.json(record);
});

// DELETE /lawful-basis/:id
lawfulBasisRouter.delete('/:id', async (req, res) => {
  const { id } = req.params;

  // {{#if ORM=prisma}}
  const existing = await prisma.lawfulBasisRecord.findUnique({ where: { id } });
  if (!existing) {
    return res.status(404).json({ error: 'Lawful basis record not found' });
  }

  await prisma.lawfulBasisRecord.delete({ where: { id } });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'lawful-basis',
      action: 'deleted',
      entityId: id,
      entityType: 'LawfulBasisRecord',
      changes: { activityName: existing.activityName },
    },
  });
  // {{/if}}
  // {{#if ORM=drizzle}}
  const [existing] = await db.select().from(lawfulBasisRecords).where(eq(lawfulBasisRecords.id, id)).limit(1);
  if (!existing) {
    return res.status(404).json({ error: 'Lawful basis record not found' });
  }

  await db.delete(lawfulBasisRecords).where(eq(lawfulBasisRecords.id, id));

  await db.insert(complianceAuditLog).values({
    module: 'lawful-basis',
    action: 'deleted',
    entityId: id,
    entityType: 'LawfulBasisRecord',
    changes: { activityName: existing.activityName },
  });
  // {{/if}}
  // {{#if ORM=none}}
  const existing = lawfulBasisStore.get(id);
  if (!existing) {
    return res.status(404).json({ error: 'Lawful basis record not found' });
  }
  lawfulBasisStore.delete(id);
  auditLog.push({ id: newId(), module: 'lawful-basis', action: 'deleted', entityId: id, at: new Date() });
  // {{/if}}

  return res.json({ success: true });
});
