/**
 * Next.js App Router — DPIA (Data Protection Impact Assessment) Route
 * Generated by create-ndpr for: {{ORG_NAME}}
 *
 * NDPA §28 — a DPIA must be conducted where processing is likely
 * to result in a high risk to the rights and freedoms of data subjects.
 *
 * Endpoints:
 *   GET    /api/dpia               — List DPIA records (optional ?status= filter)
 *   GET    /api/dpia?id=xxx        — Get a single DPIA record
 *   POST   /api/dpia               — Create a new DPIA record
 *   PUT    /api/dpia               — Update an existing DPIA record
 *   DELETE /api/dpia?id=xxx        — Delete a DPIA record
 */

import { NextRequest, NextResponse } from 'next/server';
// {{#if ORM=prisma}}
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
// {{/if}}
// {{#if ORM=drizzle}}
import { db } from '@/drizzle';
import { dpiaRecords, complianceAuditLog } from '@/drizzle/ndpr-schema';
import { eq, desc } from 'drizzle-orm';
// {{/if}}
// {{#if ORM=none}}
// TODO ({{ORG_NAME}}): wire this to your persistent store of choice. The
// in-memory map below is enough to develop against locally but DOES NOT
// satisfy NDPA Section 44 (record-keeping) or the auditability NDPC asks
// about. Replace `dpiaStore`/`auditLog` with your DB / KV / API.
interface DPIARecord {
  id: string;
  projectName: string;
  description: string;
  dpiaData: unknown;
  overallRisk: string;
  score: number;
  status: string;
  conductedBy: string;
  approvedBy: string | null;
  createdAt: Date;
  updatedAt: Date;
}
const dpiaStore = new Map<string, DPIARecord>();
const auditLog: Array<{ id: string; module: string; action: string; entityId: string; at: Date }> = [];
function newId() { return crypto.randomUUID(); }
// {{/if}}

// GET /api/dpia?status=draft  OR  /api/dpia?id=xxx
export async function GET(req: NextRequest) {
  const id = req.nextUrl.searchParams.get('id');

  if (id) {
    // {{#if ORM=prisma}}
    const record = await prisma.dPIARecord.findUnique({ where: { id } });
    // {{/if}}
    // {{#if ORM=drizzle}}
    const [record] = await db.select().from(dpiaRecords).where(eq(dpiaRecords.id, id)).limit(1);
    // {{/if}}
    // {{#if ORM=none}}
    const record = dpiaStore.get(id) ?? null;
    // {{/if}}

    if (!record) {
      return NextResponse.json({ error: 'DPIA record not found' }, { status: 404 });
    }
    return NextResponse.json(record);
  }

  const status = req.nextUrl.searchParams.get('status');

  // {{#if ORM=prisma}}
  const records = await prisma.dPIARecord.findMany({
    where: status ? { status } : undefined,
    orderBy: { createdAt: 'desc' },
  });
  // {{/if}}
  // {{#if ORM=drizzle}}
  const records = status
    ? await db.select().from(dpiaRecords).where(eq(dpiaRecords.status, status)).orderBy(desc(dpiaRecords.createdAt))
    : await db.select().from(dpiaRecords).orderBy(desc(dpiaRecords.createdAt));
  // {{/if}}
  // {{#if ORM=none}}
  const records = [...dpiaStore.values()]
    .filter((r) => (status ? r.status === status : true))
    .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
  // {{/if}}

  return NextResponse.json(records);
}

// POST /api/dpia
export async function POST(req: NextRequest) {
  const body = await req.json();
  const {
    projectName,
    description,
    dpiaData,
    overallRisk,
    score,
    conductedBy,
    approvedBy,
  } = body;

  if (!projectName || !description || !dpiaData || !overallRisk || score == null || !conductedBy) {
    return NextResponse.json(
      { error: 'projectName, description, dpiaData, overallRisk, score, and conductedBy are required' },
      { status: 400 },
    );
  }

  // {{#if ORM=prisma}}
  const record = await prisma.dPIARecord.create({
    data: {
      projectName,
      description,
      dpiaData,
      overallRisk,
      score,
      status: 'draft',
      conductedBy,
      approvedBy: approvedBy ?? null,
    },
  });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'dpia',
      action: 'created',
      entityId: record.id,
      entityType: 'DPIARecord',
      changes: { projectName, overallRisk, score, status: 'draft' },
    },
  });
  // {{/if}}
  // {{#if ORM=drizzle}}
  const [record] = await db.insert(dpiaRecords).values({
    projectName,
    description,
    dpiaData,
    overallRisk,
    score,
    status: 'draft',
    conductedBy,
    approvedBy: approvedBy ?? null,
  }).returning();

  await db.insert(complianceAuditLog).values({
    module: 'dpia',
    action: 'created',
    entityId: record.id,
    entityType: 'DPIARecord',
    changes: { projectName, overallRisk, score, status: 'draft' },
  });
  // {{/if}}
  // {{#if ORM=none}}
  const now = new Date();
  const record: DPIARecord = {
    id: newId(),
    projectName,
    description,
    dpiaData,
    overallRisk,
    score,
    status: 'draft',
    conductedBy,
    approvedBy: approvedBy ?? null,
    createdAt: now,
    updatedAt: now,
  };
  dpiaStore.set(record.id, record);
  auditLog.push({ id: newId(), module: 'dpia', action: 'created', entityId: record.id, at: new Date() });
  // {{/if}}

  return NextResponse.json(record, { status: 201 });
}

// PUT /api/dpia
export async function PUT(req: NextRequest) {
  const body = await req.json();
  const { id, ...data } = body;

  if (!id) {
    return NextResponse.json({ error: 'id is required' }, { status: 400 });
  }

  // {{#if ORM=prisma}}
  const existing = await prisma.dPIARecord.findUnique({ where: { id } });
  if (!existing) {
    return NextResponse.json({ error: 'DPIA record not found' }, { status: 404 });
  }

  const record = await prisma.dPIARecord.update({
    where: { id },
    data,
  });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'dpia',
      action: 'updated',
      entityId: record.id,
      entityType: 'DPIARecord',
      changes: data,
    },
  });
  // {{/if}}
  // {{#if ORM=drizzle}}
  const [existing] = await db.select().from(dpiaRecords).where(eq(dpiaRecords.id, id)).limit(1);
  if (!existing) {
    return NextResponse.json({ error: 'DPIA record not found' }, { status: 404 });
  }

  const [record] = await db.update(dpiaRecords).set(data).where(eq(dpiaRecords.id, id)).returning();

  await db.insert(complianceAuditLog).values({
    module: 'dpia',
    action: 'updated',
    entityId: record.id,
    entityType: 'DPIARecord',
    changes: data,
  });
  // {{/if}}
  // {{#if ORM=none}}
  const existing = dpiaStore.get(id);
  if (!existing) {
    return NextResponse.json({ error: 'DPIA record not found' }, { status: 404 });
  }
  const record: DPIARecord = { ...existing, ...data, id, updatedAt: new Date() };
  dpiaStore.set(id, record);
  auditLog.push({ id: newId(), module: 'dpia', action: 'updated', entityId: record.id, at: new Date() });
  // {{/if}}

  return NextResponse.json(record);
}

// DELETE /api/dpia?id=xxx
export async function DELETE(req: NextRequest) {
  const id = req.nextUrl.searchParams.get('id');

  if (!id) {
    return NextResponse.json({ error: 'id is required' }, { status: 400 });
  }

  // {{#if ORM=prisma}}
  const existing = await prisma.dPIARecord.findUnique({ where: { id } });
  if (!existing) {
    return NextResponse.json({ error: 'DPIA record not found' }, { status: 404 });
  }

  await prisma.dPIARecord.delete({ where: { id } });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'dpia',
      action: 'deleted',
      entityId: id,
      entityType: 'DPIARecord',
      changes: { projectName: existing.projectName },
    },
  });
  // {{/if}}
  // {{#if ORM=drizzle}}
  const [existing] = await db.select().from(dpiaRecords).where(eq(dpiaRecords.id, id)).limit(1);
  if (!existing) {
    return NextResponse.json({ error: 'DPIA record not found' }, { status: 404 });
  }

  await db.delete(dpiaRecords).where(eq(dpiaRecords.id, id));

  await db.insert(complianceAuditLog).values({
    module: 'dpia',
    action: 'deleted',
    entityId: id,
    entityType: 'DPIARecord',
    changes: { projectName: existing.projectName },
  });
  // {{/if}}
  // {{#if ORM=none}}
  const existing = dpiaStore.get(id);
  if (!existing) {
    return NextResponse.json({ error: 'DPIA record not found' }, { status: 404 });
  }
  dpiaStore.delete(id);
  auditLog.push({ id: newId(), module: 'dpia', action: 'deleted', entityId: id, at: new Date() });
  // {{/if}}

  return NextResponse.json({ success: true });
}
