/**
 * Next.js App Router — DPIA (Data Protection Impact Assessment) Route
 * Generated by create-ndpr for: {{ORG_NAME}}
 *
 * NDPA §34(3) — a DPIA must be conducted where processing is likely
 * to result in a high risk to the rights and freedoms of data subjects.
 *
 * Endpoints:
 *   GET    /api/dpia               — List DPIA records (optional ?status= filter)
 *   GET    /api/dpia?id=xxx        — Get a single DPIA record
 *   POST   /api/dpia               — Create a new DPIA record
 *   PUT    /api/dpia               — Update an existing DPIA record
 *   DELETE /api/dpia?id=xxx        — Delete a DPIA record
 */

import { NextRequest, NextResponse } from 'next/server';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// GET /api/dpia?status=draft  OR  /api/dpia?id=xxx
export async function GET(req: NextRequest) {
  const id = req.nextUrl.searchParams.get('id');

  if (id) {
    const record = await prisma.dPIARecord.findUnique({ where: { id } });
    if (!record) {
      return NextResponse.json({ error: 'DPIA record not found' }, { status: 404 });
    }
    return NextResponse.json(record);
  }

  const status = req.nextUrl.searchParams.get('status');

  const records = await prisma.dPIARecord.findMany({
    where: status ? { status } : undefined,
    orderBy: { createdAt: 'desc' },
  });

  return NextResponse.json(records);
}

// POST /api/dpia
export async function POST(req: NextRequest) {
  const body = await req.json();
  const {
    projectName,
    description,
    dpiaData,
    overallRisk,
    score,
    conductedBy,
    approvedBy,
  } = body;

  if (!projectName || !description || !dpiaData || !overallRisk || score == null || !conductedBy) {
    return NextResponse.json(
      { error: 'projectName, description, dpiaData, overallRisk, score, and conductedBy are required' },
      { status: 400 },
    );
  }

  const record = await prisma.dPIARecord.create({
    data: {
      projectName,
      description,
      dpiaData,
      overallRisk,
      score,
      status: 'draft',
      conductedBy,
      approvedBy: approvedBy ?? null,
    },
  });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'dpia',
      action: 'created',
      entityId: record.id,
      entityType: 'DPIARecord',
      changes: { projectName, overallRisk, score, status: 'draft' },
    },
  });

  return NextResponse.json(record, { status: 201 });
}

// PUT /api/dpia
export async function PUT(req: NextRequest) {
  const body = await req.json();
  const { id, ...data } = body;

  if (!id) {
    return NextResponse.json({ error: 'id is required' }, { status: 400 });
  }

  const existing = await prisma.dPIARecord.findUnique({ where: { id } });
  if (!existing) {
    return NextResponse.json({ error: 'DPIA record not found' }, { status: 404 });
  }

  const record = await prisma.dPIARecord.update({
    where: { id },
    data,
  });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'dpia',
      action: 'updated',
      entityId: record.id,
      entityType: 'DPIARecord',
      changes: data,
    },
  });

  return NextResponse.json(record);
}

// DELETE /api/dpia?id=xxx
export async function DELETE(req: NextRequest) {
  const id = req.nextUrl.searchParams.get('id');

  if (!id) {
    return NextResponse.json({ error: 'id is required' }, { status: 400 });
  }

  const existing = await prisma.dPIARecord.findUnique({ where: { id } });
  if (!existing) {
    return NextResponse.json({ error: 'DPIA record not found' }, { status: 404 });
  }

  await prisma.dPIARecord.delete({ where: { id } });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'dpia',
      action: 'deleted',
      entityId: id,
      entityType: 'DPIARecord',
      changes: { projectName: existing.projectName },
    },
  });

  return NextResponse.json({ success: true });
}
