/**
 * Next.js App Router — Breach Notification Route
 * Generated by create-ndpr for: {{ORG_NAME}}
 *
 * NDPA §40 — data controllers must notify the NDPC within 72 hours of
 * discovering a breach that poses a risk to data subject rights and freedoms.
 *
 * Endpoints:
 *   GET  /api/breach             — List breach reports (optional ?status= filter)
 *   POST /api/breach             — Create a new breach report
 */

import { NextRequest, NextResponse } from 'next/server';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

function calculateSeverity(
  category: string,
  estimatedAffected?: number,
): 'critical' | 'high' | 'medium' | 'low' {
  const highRisk = ['unauthorized_access', 'ransomware', 'data_exfiltration', 'identity_theft'];
  if (highRisk.includes(category)) {
    return (estimatedAffected ?? 0) > 1000 ? 'critical' : 'high';
  }
  if ((estimatedAffected ?? 0) > 500) return 'high';
  if ((estimatedAffected ?? 0) > 50) return 'medium';
  return 'low';
}

// GET /api/breach?status=ongoing
export async function GET(req: NextRequest) {
  const status = req.nextUrl.searchParams.get('status');

  const reports = await prisma.breachReport.findMany({
    where: status ? { status } : undefined,
    orderBy: { reportedAt: 'desc' },
  });

  return NextResponse.json(reports);
}

// POST /api/breach
export async function POST(req: NextRequest) {
  const body = await req.json();
  const {
    title,
    description,
    category,
    discoveredAt,
    occurredAt,
    reporterName,
    reporterEmail,
    reporterDepartment,
    affectedSystems,
    dataTypes,
    estimatedAffected,
    initialActions,
  } = body;

  if (!title || !description || !category || !discoveredAt || !reporterName || !reporterEmail) {
    return NextResponse.json(
      { error: 'title, description, category, discoveredAt, reporterName, and reporterEmail are required' },
      { status: 400 },
    );
  }

  if (!Array.isArray(affectedSystems) || !Array.isArray(dataTypes)) {
    return NextResponse.json(
      { error: 'affectedSystems and dataTypes must be arrays' },
      { status: 400 },
    );
  }

  const severity = calculateSeverity(category, estimatedAffected);

  const report = await prisma.breachReport.create({
    data: {
      title,
      description,
      category,
      severity,
      status: 'ongoing',
      discoveredAt: new Date(discoveredAt),
      occurredAt: occurredAt ? new Date(occurredAt) : null,
      reporterName,
      reporterEmail,
      reporterDepartment: reporterDepartment ?? null,
      affectedSystems,
      dataTypes,
      estimatedAffected: estimatedAffected ?? null,
      initialActions: initialActions ?? null,
    },
  });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'breach',
      action: 'reported',
      entityId: report.id,
      entityType: 'BreachReport',
      changes: { title, category, severity, status: 'ongoing' },
    },
  });

  return NextResponse.json(report, { status: 201 });
}
