/**
 * Next.js App Router — Consent API Route
 * Generated by create-ndpr for: {{ORG_NAME}}
 *
 * NDPA Section 26 (consent) and Section 25 (lawful basis). Records the
 * subject's affirmative choice with the audit metadata NDPC asks for.
 *
 * Endpoints:
 *   GET    /api/consent?subjectId=xxx  — Load the active consent record
 *   POST   /api/consent                — Save new consent (revokes previous)
 *   DELETE /api/consent?subjectId=xxx  — Revoke all active consent
 */

import { NextRequest, NextResponse } from 'next/server';
// {{#if ORM=prisma}}
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
// {{/if}}
// {{#if ORM=drizzle}}
import { db } from '@/drizzle';
import { consentRecords, complianceAuditLog } from '@/drizzle/ndpr-schema';
import { eq, and, isNull, desc } from 'drizzle-orm';
// {{/if}}
// {{#if ORM=none}}
// TODO ({{ORG_NAME}}): wire this to your persistent store of choice. The
// in-memory map below is enough to develop against locally but DOES NOT
// satisfy NDPA Section 44 (record-keeping) or the auditability NDPC asks
// about. Replace `consentStore`/`auditLog` with your DB / KV / API.
interface ConsentRecord {
  id: string;
  subjectId: string;
  consents: Record<string, boolean>;
  version: string;
  method: string;
  lawfulBasis: string | null;
  ipAddress: string | null;
  userAgent: string | null;
  createdAt: Date;
  revokedAt: Date | null;
}
const consentStore = new Map<string, ConsentRecord>();
const auditLog: Array<{ id: string; module: string; action: string; entityId: string; at: Date }> = [];
function newId() { return crypto.randomUUID(); }
// {{/if}}

// GET /api/consent?subjectId=xxx
export async function GET(req: NextRequest) {
  const subjectId = req.nextUrl.searchParams.get('subjectId');

  if (!subjectId) {
    return NextResponse.json({ error: 'subjectId required' }, { status: 400 });
  }

  // {{#if ORM=prisma}}
  const record = await prisma.consentRecord.findFirst({
    where: { subjectId, revokedAt: null },
    orderBy: { createdAt: 'desc' },
  });
  // {{/if}}
  // {{#if ORM=drizzle}}
  const [record] = await db
    .select()
    .from(consentRecords)
    .where(and(eq(consentRecords.subjectId, subjectId), isNull(consentRecords.revokedAt)))
    .orderBy(desc(consentRecords.createdAt))
    .limit(1);
  // {{/if}}
  // {{#if ORM=none}}
  const record = [...consentStore.values()]
    .filter((r) => r.subjectId === subjectId && r.revokedAt === null)
    .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime())[0];
  // {{/if}}

  return NextResponse.json(record ?? null);
}

// POST /api/consent
export async function POST(req: NextRequest) {
  const body = await req.json();
  const { subjectId, consents, version, method, lawfulBasis } = body;

  if (!subjectId || !consents || !version) {
    return NextResponse.json(
      { error: 'subjectId, consents, and version are required' },
      { status: 400 },
    );
  }

  const ipAddress = req.headers.get('x-forwarded-for');
  const userAgent = req.headers.get('user-agent');

  // {{#if ORM=prisma}}
  // Revoke previously active records (immutable-audit pattern — Section 44).
  await prisma.consentRecord.updateMany({
    where: { subjectId, revokedAt: null },
    data: { revokedAt: new Date() },
  });

  const record = await prisma.consentRecord.create({
    data: { subjectId, consents, version, method: method ?? 'api', lawfulBasis: lawfulBasis ?? null, ipAddress, userAgent },
  });

  await prisma.complianceAuditLog.create({
    data: { module: 'consent', action: 'created', entityId: record.id, entityType: 'ConsentRecord', changes: { subjectId, version, consents } },
  });
  // {{/if}}
  // {{#if ORM=drizzle}}
  await db.update(consentRecords).set({ revokedAt: new Date() }).where(and(eq(consentRecords.subjectId, subjectId), isNull(consentRecords.revokedAt)));

  const [record] = await db.insert(consentRecords).values({
    subjectId, consents, version, method: method ?? 'api', lawfulBasis: lawfulBasis ?? null, ipAddress, userAgent,
  }).returning();

  await db.insert(complianceAuditLog).values({
    module: 'consent', action: 'created', entityId: record.id, entityType: 'ConsentRecord', changes: { subjectId, version, consents },
  });
  // {{/if}}
  // {{#if ORM=none}}
  // Revoke previously active records for this subject
  for (const r of consentStore.values()) {
    if (r.subjectId === subjectId && r.revokedAt === null) r.revokedAt = new Date();
  }
  const record: ConsentRecord = {
    id: newId(), subjectId, consents, version, method: method ?? 'api',
    lawfulBasis: lawfulBasis ?? null, ipAddress, userAgent,
    createdAt: new Date(), revokedAt: null,
  };
  consentStore.set(record.id, record);
  auditLog.push({ id: newId(), module: 'consent', action: 'created', entityId: record.id, at: new Date() });
  // {{/if}}

  return NextResponse.json(record, { status: 201 });
}

// DELETE /api/consent?subjectId=xxx — Section 26 withdrawal
export async function DELETE(req: NextRequest) {
  const subjectId = req.nextUrl.searchParams.get('subjectId');

  if (!subjectId) {
    return NextResponse.json({ error: 'subjectId required' }, { status: 400 });
  }

  // {{#if ORM=prisma}}
  await prisma.consentRecord.updateMany({
    where: { subjectId, revokedAt: null },
    data: { revokedAt: new Date() },
  });
  await prisma.complianceAuditLog.create({
    data: { module: 'consent', action: 'revoked', entityId: subjectId, entityType: 'ConsentRecord' },
  });
  // {{/if}}
  // {{#if ORM=drizzle}}
  await db.update(consentRecords).set({ revokedAt: new Date() }).where(and(eq(consentRecords.subjectId, subjectId), isNull(consentRecords.revokedAt)));
  await db.insert(complianceAuditLog).values({ module: 'consent', action: 'revoked', entityId: subjectId, entityType: 'ConsentRecord' });
  // {{/if}}
  // {{#if ORM=none}}
  for (const r of consentStore.values()) {
    if (r.subjectId === subjectId && r.revokedAt === null) r.revokedAt = new Date();
  }
  auditLog.push({ id: newId(), module: 'consent', action: 'revoked', entityId: subjectId, at: new Date() });
  // {{/if}}

  return NextResponse.json({ success: true });
}
