/**
 * Next.js App Router — Cross-Border Transfer Route
 * Generated by create-ndpr for: {{ORG_NAME}}
 *
 * NDPA §41–42 — transfers of personal data outside Nigeria require
 * adequate safeguards and, in some cases, NDPC approval.
 *
 * Endpoints:
 *   GET    /api/cross-border                  — List transfers (optional ?riskLevel= or ?destinationCountry= filter)
 *   GET    /api/cross-border?id=xxx           — Get a single transfer record
 *   POST   /api/cross-border                  — Register a new cross-border transfer
 *   PUT    /api/cross-border                  — Update an existing transfer record
 *   DELETE /api/cross-border?id=xxx           — Delete a transfer record
 */

import { NextRequest, NextResponse } from 'next/server';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// GET /api/cross-border?riskLevel=high  OR  /api/cross-border?id=xxx
export async function GET(req: NextRequest) {
  const id = req.nextUrl.searchParams.get('id');

  if (id) {
    const record = await prisma.crossBorderTransferRecord.findUnique({ where: { id } });
    if (!record) {
      return NextResponse.json({ error: 'Cross-border transfer record not found' }, { status: 404 });
    }
    return NextResponse.json(record);
  }

  const riskLevel = req.nextUrl.searchParams.get('riskLevel');
  const destinationCountry = req.nextUrl.searchParams.get('destinationCountry');

  const where: Record<string, string> = {};
  if (riskLevel) where.riskLevel = riskLevel;
  if (destinationCountry) where.destinationCountry = destinationCountry;

  const records = await prisma.crossBorderTransferRecord.findMany({
    where: Object.keys(where).length > 0 ? where : undefined,
    orderBy: { createdAt: 'desc' },
  });

  return NextResponse.json(records);
}

// POST /api/cross-border
export async function POST(req: NextRequest) {
  const body = await req.json();
  const {
    destinationCountry,
    recipientName,
    transferMechanism,
    safeguards,
    dataCategories,
    adequacyStatus,
    ndpcApprovalRequired,
    ndpcApprovalReference,
    riskLevel,
  } = body;

  if (
    !destinationCountry ||
    !recipientName ||
    !transferMechanism ||
    !safeguards ||
    !dataCategories ||
    !adequacyStatus ||
    !riskLevel
  ) {
    return NextResponse.json(
      {
        error:
          'destinationCountry, recipientName, transferMechanism, safeguards, dataCategories, adequacyStatus, and riskLevel are required',
      },
      { status: 400 },
    );
  }

  if (!Array.isArray(dataCategories)) {
    return NextResponse.json(
      { error: 'dataCategories must be an array' },
      { status: 400 },
    );
  }

  const record = await prisma.crossBorderTransferRecord.create({
    data: {
      destinationCountry,
      recipientName,
      transferMechanism,
      safeguards,
      dataCategories,
      adequacyStatus,
      ndpcApprovalRequired: ndpcApprovalRequired ?? false,
      ndpcApprovalReference: ndpcApprovalReference ?? null,
      riskLevel,
    },
  });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'cross-border',
      action: 'created',
      entityId: record.id,
      entityType: 'CrossBorderTransferRecord',
      changes: { destinationCountry, recipientName, riskLevel },
    },
  });

  return NextResponse.json(record, { status: 201 });
}

// PUT /api/cross-border
export async function PUT(req: NextRequest) {
  const body = await req.json();
  const { id, ...data } = body;

  if (!id) {
    return NextResponse.json({ error: 'id is required' }, { status: 400 });
  }

  const existing = await prisma.crossBorderTransferRecord.findUnique({ where: { id } });
  if (!existing) {
    return NextResponse.json({ error: 'Cross-border transfer record not found' }, { status: 404 });
  }

  const record = await prisma.crossBorderTransferRecord.update({
    where: { id },
    data,
  });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'cross-border',
      action: 'updated',
      entityId: record.id,
      entityType: 'CrossBorderTransferRecord',
      changes: data,
    },
  });

  return NextResponse.json(record);
}

// DELETE /api/cross-border?id=xxx
export async function DELETE(req: NextRequest) {
  const id = req.nextUrl.searchParams.get('id');

  if (!id) {
    return NextResponse.json({ error: 'id is required' }, { status: 400 });
  }

  const existing = await prisma.crossBorderTransferRecord.findUnique({ where: { id } });
  if (!existing) {
    return NextResponse.json({ error: 'Cross-border transfer record not found' }, { status: 404 });
  }

  await prisma.crossBorderTransferRecord.delete({ where: { id } });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'cross-border',
      action: 'deleted',
      entityId: id,
      entityType: 'CrossBorderTransferRecord',
      changes: { destinationCountry: existing.destinationCountry, recipientName: existing.recipientName },
    },
  });

  return NextResponse.json({ success: true });
}
