/**
 * Next.js App Router — DSR (Data Subject Rights) Route
 * Generated by create-ndpr for: {{ORG_NAME}}
 *
 * NDPA Part IV §34–38 — rights to access, rectification, erasure,
 * portability, and objection. All requests must be acknowledged
 * within 72 hours and fulfilled within 30 days.
 *
 * Endpoints:
 *   GET  /api/dsr               — List DSR requests (optional ?status= filter)
 *   POST /api/dsr               — Submit a new DSR request
 */

import { NextRequest, NextResponse } from 'next/server';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// GET /api/dsr?status=pending
export async function GET(req: NextRequest) {
  const status = req.nextUrl.searchParams.get('status');

  const requests = await prisma.dSRRequest.findMany({
    where: status ? { status } : undefined,
    orderBy: { submittedAt: 'desc' },
  });

  return NextResponse.json(requests);
}

// POST /api/dsr
export async function POST(req: NextRequest) {
  const body = await req.json();
  const {
    type,
    subjectName,
    subjectEmail,
    subjectPhone,
    identifierType,
    identifierValue,
    description,
  } = body;

  if (!type || !subjectName || !subjectEmail || !identifierType || !identifierValue) {
    return NextResponse.json(
      { error: 'type, subjectName, subjectEmail, identifierType, and identifierValue are required' },
      { status: 400 },
    );
  }

  // NDPA mandates a 30-day response window from date of submission.
  const dueAt = new Date();
  dueAt.setDate(dueAt.getDate() + 30);

  const request = await prisma.dSRRequest.create({
    data: {
      type,
      subjectName,
      subjectEmail,
      subjectPhone: subjectPhone ?? null,
      identifierType,
      identifierValue,
      description: description ?? null,
      status: 'pending',
      dueAt,
    },
  });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'dsr',
      action: 'submitted',
      entityId: request.id,
      entityType: 'DSRRequest',
      changes: { type, subjectEmail, status: 'pending' },
    },
  });

  return NextResponse.json(request, { status: 201 });
}
