'use client';

/**
 * NDPRLayout — generated by create-ndpr
 *
 * Wraps your app with the NDPA-compliant consent banner and provider.
 *
 * Usage in app/layout.tsx:
 *
 *   import NDPRLayout from '@/app/ndpr-layout';
 *
 *   export default async function RootLayout({ children }) {
 *     const session = await getServerSession();
 *     return (
 *       <html lang="en">
 *         <body>
 *           <NDPRLayout userId={session?.user?.id}>
 *             {children}
 *           </NDPRLayout>
 *         </body>
 *       </html>
 *     );
 *   }
 */

import React from 'react';
import { NDPRProvider } from '@tantainnovative/ndpr-toolkit/core';
import { NDPRConsent } from '@tantainnovative/ndpr-toolkit/presets';
import { apiAdapter } from '@tantainnovative/ndpr-toolkit/adapters';
import type { ConsentSettings } from '@tantainnovative/ndpr-toolkit/core';

interface NDPRLayoutProps {
  children: React.ReactNode;
  /**
   * Authenticated user ID, or a stable anonymous identifier (e.g. UUID from
   * a cookie) for unauthenticated visitors. NDPA requires consent to be
   * recorded even for anonymous users.
   */
  userId?: string;
}

export default function NDPRLayout({ children, userId }: NDPRLayoutProps) {
  const subjectId = userId ?? 'anonymous';

  // apiAdapter connects the consent banner to the /api/consent route.
  // Typed as <ConsentSettings> so the banner's onSave payload matches.
  // For server-side usage in Server Components or Route Handlers, see
  // the recipes under /docs/recipes/.
  const consentStorageAdapter = apiAdapter<ConsentSettings>(
    `/api/consent?subjectId=${subjectId}`,
    {
      credentials: 'same-origin',
      // Add a CSRF header here if your app requires one:
      // headers: () => ({ 'X-CSRF-Token': getCsrfToken() }),
    },
  );

  return (
    <NDPRProvider
      organizationName="{{ORG_NAME}}"
      dpoEmail="{{DPO_EMAIL}}"
    >
      {children}

      {/*
       * NDPA-compliant consent banner.
       * The adapter persists decisions server-side so the banner is hidden
       * on return visits without flicker or double-prompting.
       */}
      <NDPRConsent adapter={consentStorageAdapter} />
    </NDPRProvider>
  );
}
