/**
 * Next.js App Router — Cross-Border Transfer Route
 * Generated by create-ndpr for: {{ORG_NAME}}
 *
 * NDPA §41–43 — transfers of personal data outside Nigeria require
 * adequate safeguards and, in some cases, NDPC approval.
 *
 * Endpoints:
 *   GET    /api/cross-border                  — List transfers (optional ?riskLevel= or ?destinationCountry= filter)
 *   GET    /api/cross-border?id=xxx           — Get a single transfer record
 *   POST   /api/cross-border                  — Register a new cross-border transfer
 *   PUT    /api/cross-border                  — Update an existing transfer record
 *   DELETE /api/cross-border?id=xxx           — Delete a transfer record
 */

import { NextRequest, NextResponse } from 'next/server';
// {{#if ORM=prisma}}
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
// {{/if}}
// {{#if ORM=drizzle}}
import { db } from '@/drizzle';
import { crossBorderTransferRecords, complianceAuditLog } from '@/drizzle/ndpr-schema';
import { eq, and, desc, type SQL } from 'drizzle-orm';
// {{/if}}
// {{#if ORM=none}}
// TODO ({{ORG_NAME}}): wire this to your persistent store of choice. The
// in-memory map below is enough to develop against locally but DOES NOT
// satisfy NDPA Section 44 (record-keeping) or the cross-border register
// NDPC inspects under Sections 41–43. Replace `crossBorderStore`/`auditLog`
// with your DB / KV / API.
interface CrossBorderTransferRecord {
  id: string;
  destinationCountry: string;
  recipientName: string;
  transferMechanism: string;
  safeguards: string;
  dataCategories: string[];
  adequacyStatus: string;
  ndpcApprovalRequired: boolean;
  ndpcApprovalReference: string | null;
  riskLevel: string;
  createdAt: Date;
  updatedAt: Date;
}
const crossBorderStore = new Map<string, CrossBorderTransferRecord>();
const auditLog: Array<{ id: string; module: string; action: string; entityId: string; at: Date }> = [];
function newId() { return crypto.randomUUID(); }
// {{/if}}

// GET /api/cross-border?riskLevel=high  OR  /api/cross-border?id=xxx
export async function GET(req: NextRequest) {
  const id = req.nextUrl.searchParams.get('id');

  if (id) {
    // {{#if ORM=prisma}}
    const record = await prisma.crossBorderTransferRecord.findUnique({ where: { id } });
    // {{/if}}
    // {{#if ORM=drizzle}}
    const [record] = await db.select().from(crossBorderTransferRecords).where(eq(crossBorderTransferRecords.id, id)).limit(1);
    // {{/if}}
    // {{#if ORM=none}}
    const record = crossBorderStore.get(id) ?? null;
    // {{/if}}

    if (!record) {
      return NextResponse.json({ error: 'Cross-border transfer record not found' }, { status: 404 });
    }
    return NextResponse.json(record);
  }

  const riskLevel = req.nextUrl.searchParams.get('riskLevel');
  const destinationCountry = req.nextUrl.searchParams.get('destinationCountry');

  // {{#if ORM=prisma}}
  const where: Record<string, string> = {};
  if (riskLevel) where.riskLevel = riskLevel;
  if (destinationCountry) where.destinationCountry = destinationCountry;

  const records = await prisma.crossBorderTransferRecord.findMany({
    where: Object.keys(where).length > 0 ? where : undefined,
    orderBy: { createdAt: 'desc' },
  });
  // {{/if}}
  // {{#if ORM=drizzle}}
  const filters: SQL[] = [];
  if (riskLevel) filters.push(eq(crossBorderTransferRecords.riskLevel, riskLevel));
  if (destinationCountry) filters.push(eq(crossBorderTransferRecords.destinationCountry, destinationCountry));

  const records = filters.length > 0
    ? await db.select().from(crossBorderTransferRecords).where(and(...filters)).orderBy(desc(crossBorderTransferRecords.createdAt))
    : await db.select().from(crossBorderTransferRecords).orderBy(desc(crossBorderTransferRecords.createdAt));
  // {{/if}}
  // {{#if ORM=none}}
  const records = [...crossBorderStore.values()]
    .filter((r) => (riskLevel ? r.riskLevel === riskLevel : true))
    .filter((r) => (destinationCountry ? r.destinationCountry === destinationCountry : true))
    .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
  // {{/if}}

  return NextResponse.json(records);
}

// POST /api/cross-border
export async function POST(req: NextRequest) {
  const body = await req.json();
  const {
    destinationCountry,
    recipientName,
    transferMechanism,
    safeguards,
    dataCategories,
    adequacyStatus,
    ndpcApprovalRequired,
    ndpcApprovalReference,
    riskLevel,
  } = body;

  if (
    !destinationCountry ||
    !recipientName ||
    !transferMechanism ||
    !safeguards ||
    !dataCategories ||
    !adequacyStatus ||
    !riskLevel
  ) {
    return NextResponse.json(
      {
        error:
          'destinationCountry, recipientName, transferMechanism, safeguards, dataCategories, adequacyStatus, and riskLevel are required',
      },
      { status: 400 },
    );
  }

  if (!Array.isArray(dataCategories)) {
    return NextResponse.json(
      { error: 'dataCategories must be an array' },
      { status: 400 },
    );
  }

  // {{#if ORM=prisma}}
  const record = await prisma.crossBorderTransferRecord.create({
    data: {
      destinationCountry,
      recipientName,
      transferMechanism,
      safeguards,
      dataCategories,
      adequacyStatus,
      ndpcApprovalRequired: ndpcApprovalRequired ?? false,
      ndpcApprovalReference: ndpcApprovalReference ?? null,
      riskLevel,
    },
  });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'cross-border',
      action: 'created',
      entityId: record.id,
      entityType: 'CrossBorderTransferRecord',
      changes: { destinationCountry, recipientName, riskLevel },
    },
  });
  // {{/if}}
  // {{#if ORM=drizzle}}
  const [record] = await db.insert(crossBorderTransferRecords).values({
    destinationCountry,
    recipientName,
    transferMechanism,
    safeguards,
    dataCategories,
    adequacyStatus,
    ndpcApprovalRequired: ndpcApprovalRequired ?? false,
    ndpcApprovalReference: ndpcApprovalReference ?? null,
    riskLevel,
  }).returning();

  await db.insert(complianceAuditLog).values({
    module: 'cross-border',
    action: 'created',
    entityId: record.id,
    entityType: 'CrossBorderTransferRecord',
    changes: { destinationCountry, recipientName, riskLevel },
  });
  // {{/if}}
  // {{#if ORM=none}}
  const now = new Date();
  const record: CrossBorderTransferRecord = {
    id: newId(),
    destinationCountry,
    recipientName,
    transferMechanism,
    safeguards,
    dataCategories,
    adequacyStatus,
    ndpcApprovalRequired: ndpcApprovalRequired ?? false,
    ndpcApprovalReference: ndpcApprovalReference ?? null,
    riskLevel,
    createdAt: now,
    updatedAt: now,
  };
  crossBorderStore.set(record.id, record);
  auditLog.push({ id: newId(), module: 'cross-border', action: 'created', entityId: record.id, at: new Date() });
  // {{/if}}

  return NextResponse.json(record, { status: 201 });
}

// PUT /api/cross-border
export async function PUT(req: NextRequest) {
  const body = await req.json();
  const { id, ...data } = body;

  if (!id) {
    return NextResponse.json({ error: 'id is required' }, { status: 400 });
  }

  // {{#if ORM=prisma}}
  const existing = await prisma.crossBorderTransferRecord.findUnique({ where: { id } });
  if (!existing) {
    return NextResponse.json({ error: 'Cross-border transfer record not found' }, { status: 404 });
  }

  const record = await prisma.crossBorderTransferRecord.update({
    where: { id },
    data,
  });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'cross-border',
      action: 'updated',
      entityId: record.id,
      entityType: 'CrossBorderTransferRecord',
      changes: data,
    },
  });
  // {{/if}}
  // {{#if ORM=drizzle}}
  const [existing] = await db.select().from(crossBorderTransferRecords).where(eq(crossBorderTransferRecords.id, id)).limit(1);
  if (!existing) {
    return NextResponse.json({ error: 'Cross-border transfer record not found' }, { status: 404 });
  }

  const [record] = await db.update(crossBorderTransferRecords).set(data).where(eq(crossBorderTransferRecords.id, id)).returning();

  await db.insert(complianceAuditLog).values({
    module: 'cross-border',
    action: 'updated',
    entityId: record.id,
    entityType: 'CrossBorderTransferRecord',
    changes: data,
  });
  // {{/if}}
  // {{#if ORM=none}}
  const existing = crossBorderStore.get(id);
  if (!existing) {
    return NextResponse.json({ error: 'Cross-border transfer record not found' }, { status: 404 });
  }
  const record: CrossBorderTransferRecord = { ...existing, ...data, id, updatedAt: new Date() };
  crossBorderStore.set(id, record);
  auditLog.push({ id: newId(), module: 'cross-border', action: 'updated', entityId: record.id, at: new Date() });
  // {{/if}}

  return NextResponse.json(record);
}

// DELETE /api/cross-border?id=xxx
export async function DELETE(req: NextRequest) {
  const id = req.nextUrl.searchParams.get('id');

  if (!id) {
    return NextResponse.json({ error: 'id is required' }, { status: 400 });
  }

  // {{#if ORM=prisma}}
  const existing = await prisma.crossBorderTransferRecord.findUnique({ where: { id } });
  if (!existing) {
    return NextResponse.json({ error: 'Cross-border transfer record not found' }, { status: 404 });
  }

  await prisma.crossBorderTransferRecord.delete({ where: { id } });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'cross-border',
      action: 'deleted',
      entityId: id,
      entityType: 'CrossBorderTransferRecord',
      changes: { destinationCountry: existing.destinationCountry, recipientName: existing.recipientName },
    },
  });
  // {{/if}}
  // {{#if ORM=drizzle}}
  const [existing] = await db.select().from(crossBorderTransferRecords).where(eq(crossBorderTransferRecords.id, id)).limit(1);
  if (!existing) {
    return NextResponse.json({ error: 'Cross-border transfer record not found' }, { status: 404 });
  }

  await db.delete(crossBorderTransferRecords).where(eq(crossBorderTransferRecords.id, id));

  await db.insert(complianceAuditLog).values({
    module: 'cross-border',
    action: 'deleted',
    entityId: id,
    entityType: 'CrossBorderTransferRecord',
    changes: { destinationCountry: existing.destinationCountry, recipientName: existing.recipientName },
  });
  // {{/if}}
  // {{#if ORM=none}}
  const existing = crossBorderStore.get(id);
  if (!existing) {
    return NextResponse.json({ error: 'Cross-border transfer record not found' }, { status: 404 });
  }
  crossBorderStore.delete(id);
  auditLog.push({ id: newId(), module: 'cross-border', action: 'deleted', entityId: id, at: new Date() });
  // {{/if}}

  return NextResponse.json({ success: true });
}
