/**
 * Next.js App Router — Lawful Basis Route
 * Generated by create-ndpr for: {{ORG_NAME}}
 *
 * NDPA §25 — data processing must have a lawful basis. This route
 * manages a register of processing activities and their lawful bases.
 *
 * Endpoints:
 *   GET    /api/lawful-basis               — List lawful basis records (optional ?lawfulBasis= filter)
 *   GET    /api/lawful-basis?id=xxx        — Get a single record
 *   POST   /api/lawful-basis               — Create a new lawful basis record
 *   PUT    /api/lawful-basis               — Update an existing record
 *   DELETE /api/lawful-basis?id=xxx        — Delete a record
 */

import { NextRequest, NextResponse } from 'next/server';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// GET /api/lawful-basis?lawfulBasis=consent  OR  /api/lawful-basis?id=xxx
export async function GET(req: NextRequest) {
  const id = req.nextUrl.searchParams.get('id');

  if (id) {
    const record = await prisma.lawfulBasisRecord.findUnique({ where: { id } });
    if (!record) {
      return NextResponse.json({ error: 'Lawful basis record not found' }, { status: 404 });
    }
    return NextResponse.json(record);
  }

  const lawfulBasis = req.nextUrl.searchParams.get('lawfulBasis');

  const records = await prisma.lawfulBasisRecord.findMany({
    where: lawfulBasis ? { lawfulBasis } : undefined,
    orderBy: { createdAt: 'desc' },
  });

  return NextResponse.json(records);
}

// POST /api/lawful-basis
export async function POST(req: NextRequest) {
  const body = await req.json();
  const {
    activityName,
    lawfulBasis,
    justification,
    dataCategories,
    purposes,
    assessedBy,
    reviewDate,
  } = body;

  if (!activityName || !lawfulBasis || !justification || !dataCategories || !purposes || !assessedBy) {
    return NextResponse.json(
      { error: 'activityName, lawfulBasis, justification, dataCategories, purposes, and assessedBy are required' },
      { status: 400 },
    );
  }

  if (!Array.isArray(dataCategories) || !Array.isArray(purposes)) {
    return NextResponse.json(
      { error: 'dataCategories and purposes must be arrays' },
      { status: 400 },
    );
  }

  const record = await prisma.lawfulBasisRecord.create({
    data: {
      activityName,
      lawfulBasis,
      justification,
      dataCategories,
      purposes,
      assessedBy,
      reviewDate: reviewDate ? new Date(reviewDate) : null,
    },
  });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'lawful-basis',
      action: 'created',
      entityId: record.id,
      entityType: 'LawfulBasisRecord',
      changes: { activityName, lawfulBasis, assessedBy },
    },
  });

  return NextResponse.json(record, { status: 201 });
}

// PUT /api/lawful-basis
export async function PUT(req: NextRequest) {
  const body = await req.json();
  const { id, ...data } = body;

  if (!id) {
    return NextResponse.json({ error: 'id is required' }, { status: 400 });
  }

  const existing = await prisma.lawfulBasisRecord.findUnique({ where: { id } });
  if (!existing) {
    return NextResponse.json({ error: 'Lawful basis record not found' }, { status: 404 });
  }

  if (data.reviewDate) {
    data.reviewDate = new Date(data.reviewDate);
  }

  const record = await prisma.lawfulBasisRecord.update({
    where: { id },
    data,
  });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'lawful-basis',
      action: 'updated',
      entityId: record.id,
      entityType: 'LawfulBasisRecord',
      changes: data,
    },
  });

  return NextResponse.json(record);
}

// DELETE /api/lawful-basis?id=xxx
export async function DELETE(req: NextRequest) {
  const id = req.nextUrl.searchParams.get('id');

  if (!id) {
    return NextResponse.json({ error: 'id is required' }, { status: 400 });
  }

  const existing = await prisma.lawfulBasisRecord.findUnique({ where: { id } });
  if (!existing) {
    return NextResponse.json({ error: 'Lawful basis record not found' }, { status: 404 });
  }

  await prisma.lawfulBasisRecord.delete({ where: { id } });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'lawful-basis',
      action: 'deleted',
      entityId: id,
      entityType: 'LawfulBasisRecord',
      changes: { activityName: existing.activityName },
    },
  });

  return NextResponse.json({ success: true });
}
