/**
 * Next.js App Router — DSR (Data Subject Rights) Route
 * Generated by create-ndpr for: {{ORG_NAME}}
 *
 * NDPA §34 — rights to access, rectification, erasure, portability, and
 * objection. All requests must be acknowledged promptly and fulfilled
 * within the statutory window (NDPC guidance: 30 days).
 *
 * Endpoints:
 *   GET  /api/dsr               — List DSR requests (optional ?status= filter)
 *   POST /api/dsr               — Submit a new DSR request
 */

import { NextRequest, NextResponse } from 'next/server';
// {{#if ORM=prisma}}
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
// {{/if}}
// {{#if ORM=drizzle}}
import { db } from '@/drizzle';
import { dsrRequests, complianceAuditLog } from '@/drizzle/ndpr-schema';
import { eq, desc } from 'drizzle-orm';
// {{/if}}
// {{#if ORM=none}}
// TODO ({{ORG_NAME}}): wire this to your persistent store of choice. The
// in-memory map below is enough to develop against locally but DOES NOT
// satisfy NDPA Section 44 (record-keeping) or the auditability NDPC asks
// about. Replace `dsrStore`/`auditLog` with your DB / KV / API.
interface DSRRequest {
  id: string;
  type: string;
  subjectName: string;
  subjectEmail: string;
  subjectPhone: string | null;
  identifierType: string;
  identifierValue: string;
  description: string | null;
  status: string;
  submittedAt: Date;
  dueAt: Date;
}
const dsrStore = new Map<string, DSRRequest>();
const auditLog: Array<{ id: string; module: string; action: string; entityId: string; at: Date }> = [];
function newId() { return crypto.randomUUID(); }
// {{/if}}

// GET /api/dsr?status=pending
export async function GET(req: NextRequest) {
  const status = req.nextUrl.searchParams.get('status');

  // {{#if ORM=prisma}}
  const requests = await prisma.dSRRequest.findMany({
    where: status ? { status } : undefined,
    orderBy: { submittedAt: 'desc' },
  });
  // {{/if}}
  // {{#if ORM=drizzle}}
  const requests = status
    ? await db.select().from(dsrRequests).where(eq(dsrRequests.status, status)).orderBy(desc(dsrRequests.submittedAt))
    : await db.select().from(dsrRequests).orderBy(desc(dsrRequests.submittedAt));
  // {{/if}}
  // {{#if ORM=none}}
  const requests = [...dsrStore.values()]
    .filter((r) => (status ? r.status === status : true))
    .sort((a, b) => b.submittedAt.getTime() - a.submittedAt.getTime());
  // {{/if}}

  return NextResponse.json(requests);
}

// POST /api/dsr
export async function POST(req: NextRequest) {
  const body = await req.json();
  const {
    type,
    subjectName,
    subjectEmail,
    subjectPhone,
    identifierType,
    identifierValue,
    description,
  } = body;

  if (!type || !subjectName || !subjectEmail || !identifierType || !identifierValue) {
    return NextResponse.json(
      { error: 'type, subjectName, subjectEmail, identifierType, and identifierValue are required' },
      { status: 400 },
    );
  }

  // NDPA mandates a 30-day response window from date of submission.
  const dueAt = new Date();
  dueAt.setDate(dueAt.getDate() + 30);

  // {{#if ORM=prisma}}
  const request = await prisma.dSRRequest.create({
    data: {
      type,
      subjectName,
      subjectEmail,
      subjectPhone: subjectPhone ?? null,
      identifierType,
      identifierValue,
      description: description ?? null,
      status: 'pending',
      dueAt,
    },
  });

  await prisma.complianceAuditLog.create({
    data: {
      module: 'dsr',
      action: 'submitted',
      entityId: request.id,
      entityType: 'DSRRequest',
      changes: { type, subjectEmail, status: 'pending' },
    },
  });
  // {{/if}}
  // {{#if ORM=drizzle}}
  const [request] = await db.insert(dsrRequests).values({
    type,
    subjectName,
    subjectEmail,
    subjectPhone: subjectPhone ?? null,
    identifierType,
    identifierValue,
    description: description ?? null,
    status: 'pending',
    dueAt,
  }).returning();

  await db.insert(complianceAuditLog).values({
    module: 'dsr',
    action: 'submitted',
    entityId: request.id,
    entityType: 'DSRRequest',
    changes: { type, subjectEmail, status: 'pending' },
  });
  // {{/if}}
  // {{#if ORM=none}}
  const request: DSRRequest = {
    id: newId(),
    type,
    subjectName,
    subjectEmail,
    subjectPhone: subjectPhone ?? null,
    identifierType,
    identifierValue,
    description: description ?? null,
    status: 'pending',
    submittedAt: new Date(),
    dueAt,
  };
  dsrStore.set(request.id, request);
  auditLog.push({ id: newId(), module: 'dsr', action: 'submitted', entityId: request.id, at: new Date() });
  // {{/if}}

  return NextResponse.json(request, { status: 201 });
}
