/**
 * Shared legal-notice strings for compliance artifacts produced by this toolkit.
 *
 * Everything this library generates — privacy policies, DPIA reports, breach
 * notifications, RoPA exports, compliance-score outputs — is *guidance* based on
 * the gazetted text of the Nigeria Data Protection Act 2023 and publicly
 * available NDPC guidance. It is not legal advice and must not be relied on as
 * a substitute for review by a qualified Nigerian privacy lawyer or your
 * organisation's DPO.
 */

/**
 * Short disclaimer suitable for component captions and dashboard footers.
 * One line, no markdown.
 */
export const LEGAL_DISCLAIMER_SHORT =
  'Generated for guidance only. Not legal advice — verify with your DPO or counsel.';

/**
 * Full disclaimer suitable for PDF/DOCX footers and exported artifacts.
 */
export const LEGAL_DISCLAIMER_LONG =
  'This document is generated by @tantainnovative/ndpr-toolkit for guidance ' +
  'purposes only. It is not legal advice and does not constitute a formal ' +
  'compliance opinion. NDPA 2023 section references reflect the gazetted text ' +
  'and may evolve as the Nigeria Data Protection Commission (NDPC) issues ' +
  'further regulations, directives, or guidance under Section 61 / Section 62. ' +
  'Verify the current position with your Data Protection Officer or qualified ' +
  'Nigerian privacy counsel before acting on this output.';

/**
 * Returns the long disclaimer wrapped with a leading heading suitable for
 * embedding at the foot of an exported document.
 */
export function legalDisclaimerBlock(heading = 'Important Notice'): string {
  return `${heading}\n${'='.repeat(heading.length)}\n${LEGAL_DISCLAIMER_LONG}\n`;
}
